<?php
$title = $this->translate('Features');
$this->headTitle($title);
?>
<h1><?php echo $title; ?></h1>
<p>
    <?php echo $this->translate('At Learnlists you can:'); ?>
</p>
<ul>
    <li>
        <?php echo $this->translate('learn with the best quality quizes'); ?>
    </li>
    <li>
        <?php echo $this->translate('use a great and intelligent tool to learn from quizes'); ?>
    </li>
    <li>
        <?php echo $this->translate('create you own quiz'); ?>
    </li>
</ul>