<?php
$title = $this->translate('How does it work?');
$this->headTitle($title);
$this->headTitle($this->translate('teacher'));
?>

<h1><?php echo $this->translate('Use the best tool for your lerners to learn quizz'); ?></h1>
<br/>
<ul class="nav nav-tabs">
  <li class="active">
    <a href="#create_list" data-toggle="tab"><?php echo $this->translate('I would like to create a new list'); ?></a>
  </li>
  <li>
      <a href="#lerner_use_my_lists" data-toggle="tab"><?php echo $this->translate('I would like my lerners to be able to use my lists'); ?></a>
  </li>
</ul>

<div id="myTabContent" class="tab-content">
    <div class="tab-pane fade in active" id="create_list">
        <p><?php echo $this->translate('As a teacher, your lists will be identified as coming from a professional and therefore with high quality standards.'); ?></p>
        <?php echo $this->partial('lrnl-help/help-static/how_to_create_a_list.phtml'); ?>
    </div>
    <div class="tab-pane fade" id="lerner_use_my_lists">
        <p><?php echo $this->translate('There is nothing special to do. Your lists are immediately available for your lerners and any other user.'); ?></p>        
    </div>
</div>
    


