<?php foreach ($filter->getElements() as $range): 
       $range->setAttribute('data-url',$this->url('lrnl-search',[],['query' => $range->getQueryUrl()]));
   ?>
   <div class="filter-search filter-search-range">
       <a type="button" data-toggle="collapse" data-target="#<?php $name = 'collapse'.$range->getName();echo $name; ?>">
            <h5 class="well"><?php echo ucfirst($this->translate($range->getLabel())); ?></h5>
       </a>               
       <div class="collapse in filter-choice" id="<?php echo $name; ?>">
           <div class="well">
               <span class="min-slider label label-important pull-left"></span>
               <span class="max-slider label label-important pull-right"></span>
               <?php echo $this->formInput($range); ?>  
           </div>
       </div>
   </div>
   <?php endforeach; ?>