<div class="<?php echo $wrapClass; ?>">
    <div class="row-fluid">
        <a href="<?php echo $href; ?>">
            <div class="span12 well">
                <div class="span4"><?php echo $image; ?></div>
                <div class="span8">
                    <h4><?php echo $title; ?></h4>
                    <p class="muted"><?php echo $subTitle; ?></p>
                </div>
            </div>
        </a>
    </div>
</div>
   