<?php 

$options = [    
    'nbElementPerline' => 4,
    'nbMaxLine' => 2,
    'openingTags' => '<div class="row-fluid"><ul class="thumbnails home">',
    'closingTags' => '</ul></div>'
];

$elements = [];
foreach ($categories as $category) {
    $imgUrl = $imgUrl = $this->listquestPictureUrl()->getCategoryUrl($category);
    $imgAlt = ucfirst($this->escapeHtml($category->getName()));
    $href = $this->url('lrnl-search',[],['query' => [
            'category' => $category->getId().'-'.$category->getName(),
        ]]);
    $thumbnailAttribs = [
        'src' => $imgUrl,
        'alt' => $imgAlt,
        'title' => sprintf($this->translate('Quiz: %s'),$imgAlt),
    ];
    $elements[] = (string)$this->partial('lrnl-listquests/listquest/home/categoryBox.phtml',[
        'href' => $href,
        'title' => $category->getName(),
        'subTitle' => $category->getDescription(),
        'image' =>$this->thumbnail($thumbnailAttribs,['size'=>'XS']),
        'wrapClass' =>'span3 choice-box',
     ]);
    
    
}

echo $this->thumbLine($elements,$options);?>
