<?php 
if (!isset($thumbLinesMax)){
    $thumbLinesMax = 2;
}
$thumbs = '';
$thumbLines = 0;
foreach ($categories as $category) {
    $imgUrl = $this->listquestPictureUrl()->getCategoryUrl($category);
    $imgAlt = ucfirst($this->escapeHtml($category));
    $href = $this->url('lrnl-search',[],['query' => [
        'category' => $category->getName(),
    ]]);
    $titleText = ucfirst($this->escapeHtml($category));
    $closingTags = '</ul></div>'."\n";
    $thumbs .=$this->cycle(['<div class="row-fluid"><ul class="thumbnails home">','','',''],'openTag')->next();
    $thumbs .= $this->partial('lrnl-listquests/listquest/thumbnail.phtml',[
        'imgUrl' => $imgUrl,
        'imgAlt' => $imgAlt,
        'titleText' => $titleText,
        'href' => $href
    ]);
    $end = $this->cycle(['','','',$closingTags],'closingTag')->next();
    $thumbs .= $end;   
    $thumbLines += (string)$this->cycle([0,0,0,1],'nbLine')->next();
    if ($thumbLines === $thumbLinesMax){
        break;
    }
}

if (!(string)$end){
    $thumbs .= $closingTags; 
}
?>

<?php echo $thumbs;?>