<?php if ($this->pageCount): ?>
<div class="pagination pull-right pagination-small">
    <ul>

        <!-- First page link -->
        <li<?php echo (isset($this->previous)) ? '' : ' class="disabled"'; ?>>
            <a href="<?php echo $this->url($this->route, array('page' => $this->first),['query'=>$this->query]); ?>">&lt;&lt; </a>
        </li>

        
        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>
        <li<?php echo ($page == $this->current) ? ' class="active"' : ''; ?>>
            <a href="<?php echo $this->url($this->route, array('page' => $page),['query'=>$this->query]); ?>"><?php echo $page; ?></a>
        </li>
        <?php endforeach; ?>

        
        <!-- Last page link -->
        <li<?php echo (isset($this->next)) ? '' : ' class="disabled"'; ?>>
            <a href="<?php echo $this->url($this->route, array('page' => $this->last),['query'=>$this->query]); ?>"> &gt;&gt;</a>
        </li>

    </ul>
</div>
<?php endif; ?>