<h1><?php echo $this->translate('Step 1: Email Verification'); ?></h1>
<?php
if(!$this->enableRegistration)
{
    print '<div class="alert alert-error">Registration is disabled</div>';
    return;
}

$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/register/step1'));
$form->setAttribute('method', 'POST');

echo $this->form()->openTag($form);
?>


<?php foreach ($form->getElements() as $element) { ?>
    <?php if ($element->getLabel() != null) { ?>
    <?php echo $this->formLabel($element); ?>
    <?php } ?>
    <?php if ($element->getAttribute('type') !== 'submit') { ?>
    <?php echo $this->formInput($element) . $this->formElementErrors($element); ?>
    <?php } else {?>
<div class="form-actions">
     <?php echo $this->formInput($element) . $this->formElementErrors($element); ?>
</div>
<?php } ?>
<?php } ?>


<?php $this->url('zfcuser/register/step1'); ?>
