<h1><?php echo $this->translate('Step 1: Email Verification'); ?></h1>
<?php
if(!$this->enableRegistration)
{
    print '<div class="alert alert-error">Registration is disabled</div>';
    return;
}

$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/register/step1'));
$form->setAttribute('method', 'POST');
$form->get('email_address')->setLabel(_('Email address'));
$form->get('submit')->setValue(_('Verify Email Address'));

if ($form->getMessages()):
?>
    <div class="alert alert-error">
        <button class="close" data-dismiss="alert" type="button">×</button>
        <strong><?php echo $this->translate('Please try again!'); ?></strong>
    </div>
<?php
endif;
echo $this->formTwb($form, \DluTwBootstrap\Form\FormUtil::FORM_TYPE_VERTICAL,['elements' => ['submit' => ['class' => 'btn-primary']]]);
echo $this->translate('Value is required and can\'t be empty');