<?php
$title = $this->translate('Edit question');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form->setAttribute('action', $this->url('listquests/question/edit',[
        'id'     => $this->id,
]));
$form->prepare();

echo $this->form()->openTag($form);
$question = $form->get('question');
echo $this->formHidden($question->get('id'));
echo $this->formRow($question->get('text'));?>
<span class="help-inline">
    (<a href="#" data-toggle="tooltip" data-placement="right" title="<?php echo $this->translate('Enter the text for the question. If this is a sentence to fill in, please use two "%" signs in order to specify answers.Example : He %was% not there %either%.'); ?>">?</a>)
</span>
<?php echo $this->formRow($question->get('answer'));?>
<span class="help-inline">
    (<a href="#" data-toggle="tooltip" data-placement="right" title="<?php echo $this->translate('Nothing to enter if the answer was already entered directly in the text.'); ?>">?</a>)
</span>
<?php echo $this->formRow($question->get('tip'));?>
<div class="form-actions">
    <?php echo $this->formSubmit($form->get('submit'));?>
</div>
<?php echo $this->form()->closeTag();




