<?php
$title = $this->translate('About us');
$this->headTitle($title);
?>
<div class="row-fluid">
    <div class="well well-large">
        <h1><?php echo $title; ?></h1>
        <h2>
            Learlists, quiz-list provider for a quality sustainable learning.
        </h2>
        <p>Learlists has been developed in order to help student of any person who would like be learn systematically and efficiently.</p>
        <p>Learning is forgetting and learning again, learning through lists helps to make learning sustainable.</p>
    </div>
</div>


