<h1>Help</h1>
<ul>
    <h3>Lists (for students)</h3>
    <li>
        <h4>Can I add a new list ?</h4>
        <p>Yes it is possible, but you have to be logged in. Once you are logged in you can create as many lists as you wish and add questions.</p>
    </li>
    <li>
        <h4>How can I find the list with the best questions ?</h4>
        <p>Our goal is to provide the best lists to the student. The seach engine enables to search though the lists prepared only by teachers in order to ensure their quality. Moreover every list is rated by its users so that you can easily identify the best lists.</p>
    </li>
</ul>
<ul>
    <h3>Learning : question-answer (for students)</h3>
    <li>
        <h4>How is the score calculated ?</h4>
        <p>For each question, the way you anwer is analysed and recorded by Learnlists in order to optimize your learning as you go through the quiz several times (rounds). Each answer corresponds to one of five different types of answer : answer right in less than 10 seconds,... </p>
    </li>
    <li>
        <h4>What are the rounds ?</h4>
        <p>A round consists of answering to all the question of a list. We consider that repeating several rounds allow to learn efficiently.</p>
    </li>
</ul>
