<hgroup>
    <h1>Privacy Policy</h1>
    <h2>Updated: XX</h2>
</hgroup>

<p>Your privacy is critically important to us. At Learnlists we have a few fundamental principles:</p>

<ul>
<li>We don&#8217;t ask you for personal information unless we truly need it.</li>
<li>We don&#8217;t share your personal information with anyone except to comply with the law, develop our products, or protect our rights.</li>
<li>We don&#8217;t store personal information on our servers unless required for the on-going operation of one of our services.</li>
<li>We aim to make it as simple as possible for you to control what&#8217;s visible to the public, seen by search engines, kept private, and 	permanently deleted.</li>
</ul>

<p>It is Learnlists's policy to respect your privacy regarding any information we may collect while operating our website.</p>
<p>This privacy statement describes how Learnlists XXX("<b>Learnlists</b>") collects and uses the personal information you provide on our Web site: <a href="http://quizlet.com" target="_blank">quizlet.com</a>. It also describes the choices available to you regarding our use of your personal 	information and how you can access and update this information.</p>

<p>Like most website operators, Learnlists collects non-personally-identifying information of the sort that web browsers and servers typically make available, such as the browser type, language preference, referring site, and the date and time of each visitor request. Learnlists&#8217;s 	purpose in collecting non-personally identifying information is to better understand how Learnlists&#8217;s visitors use its website. From time to 	time, Learnlists may release non-personally-identifying information in the aggregate, e.g., by publishing a report on trends in the usage of its 	website.</p>
<p>Learnlists also collects potentially personally-identifying information like Internet Protocol (IP) addresses. Learnlists does not use such information to identify its visitors, however, and does not disclose such information, other than under the same circumstances that it uses and 	discloses personally-identifying information, as described below.</p>

<h3>Gathering of Personally-Identifying Information</h3>

<h3>Children</h3>

<h3>Safety on Learnlists</h3>

<h3>Aggregated Statistics</h3>

<h3>How We Handle Personally Identifiable Information</h3>

<h3>Parental Rights</h3>

<h3>Class Discussions and Profile</h3>

<h3>Cookies</h3>
<p>A cookie is a string of information that a website stores on a visitor's computer, and that the visitor's browser provides to the website 	each time the visitor returns. Learnlists uses cookies to help Learnlists identify and track visitors, their usage of Learnlists website, and their 	website access preferences. Learnlists visitors who do not wish to have cookies placed on their computers should set their browsers to refuse 	cookies before using Learnlists's website, with the drawback that certain features of Learnlists's website may not function properly without the aid 	of cookies.</p>

<h3>Advertising on Learnlists</h3>

<h3>Web Beacons</h3>

<h3>How to Update your Information</h3>


<h3>Security</h3>

<h3>Data Retention</h3>

<h3>Contact Us</h3>
<p>If you have questions or wish to send us comments about this Privacy Policy, please send an email to XX or write us:</p>
<p>Attention Privacy<br />
XX<br />


<h3>Privacy Policy Changes</h3>
<p>Learnlists reserves the right to modify this privacy statement at any time, so please review it frequently. If we change how we use your 	personally identifiable information, we will notify, by email, and/ or by means of a notice on our Web site.</p>
