 <h1>Terms of Service</h1>
<h2>Updated: XXX</h2>

<p>The Learnlists website ("<strong>Service</strong>") is a hosted service operated by Learnlists XXX ("<strong>Learnlists</strong>"). Any use of the Service is subject to the following Terms and Conditions of Use ("<strong>Terms and Conditions</strong>"), as well as to <a href="/privacy/">Learnlists's Privacy Policy</a>, all of which are incorporated by reference into these Terms and Conditions. Your use of the Service will constitute your acceptance of these terms and conditions.</p>
