<?php

$title = $this->translate('Learn at LearnLists');
$this->headTitle($title);
$this->headMeta()->appendName('description', $this->translate('Search to find the best quizes to learn what you wish from lists of questions prepared by our community of teachers.'));
$paginationControl = $this->paginationControl(
    $lists,
    'Sliding',
    'pagination_control',
    ['route' => 'lrnl-search','query' => $query]
);
?>

<div class="row-fluid search_bar_top">
    <div class="span12">
        <div class="row-fluid  well well-small">
            <?php echo $this->listSearchBar($searchForm); ?>
        </div>
    </div>
</div>
<div class="row-fluid search_engine">
    <div class="span3">
        <div class="span11 well" id="left_side_filters">
            <?php echo $this->filterForm($filterForm); ?>
        </div>
    </div>
    <div class="span9" id="search_results_body">
        <div class="row-fluid  well well-small" id="search_result_summary">
            <?php echo sprintf($this->translate('%s results'),$resultNb); ?>                      
        </div>
        <div class="row-fluid">
            <?php echo $this->formRow($filterForm->get('filters')); ?>              
        </div>
        <hr>
        <div class="row-fluid">
            <div class="row-fluid">
               <ul id="search_result_lists">
                    <?php echo $this->listquestCollection($lists); ?>               
                </ul> 
            </div>
            <div class="row-fluid">
                <div class="span6">
                    <button id="comment-button" type="button" class="btn" data-toggle="collapse" data-target="#comment">
                        <i class="icon-comment"></i> <?php echo $this->translate('Leave a comment!') ?>
                    </button>
                </div>
                <div class="span6">
                    <?php echo $paginationControl ?>
                </div>
            </div>
            <div class="row-fluid">
                <div id="comment" class="collapse">
                <?php echo $this->disqus(); ?>
                </div>
            </div>
        </div>
    </div>
</div>
        