<?php

$title = $this->translate('Learn at LearnLists');
$this->headTitle($title);
$this->placeholder('header')->captureStart();
$this->headScript()->appendFile($this->basePath() . '/js/lib/jquery.datatable.min.js');
$this->headScript()->appendFile($this->basePath() . '/js/lib/bootstrap-slider.js');
$this->headLink()->prependStylesheet($this->basePath() . '/css/vendor/slider.css');
$searchForm->setAttribute('action', $this->url('lrnl-search'));
$searchForm->prepare();
?>

<div class="row-fluid search_bar_top">
    <div class="span12">
        <div class="row-fluid  well well-small">
            <?php echo $this->form()->openTag($searchForm);?>
            <?php echo $this->formRow($searchForm->get('search')); ?>
            <?php echo $this->formRow($searchForm->get('language')); ?>
            <button type="submit" class="btn btn-large btn-primary"><i class="icon-white icon-search"></i> <?php echo $this->translate('Search'); ?></button>
            <?php echo $this->form()->closeTag();?> 
        </div>
    </div>
</div>
<div class="row-fluid search_engine">
    <div class="span3 left_side_filters">        
        <?php foreach ($filtersShow['filterTerm'] as $filter => $values): ?>
        <div class="filter-search">
            <h4><?php echo $this->translate($filter); ?></h4>
            <div class="filter-choice">
                <?php foreach ($values as $value): ?>
                <label class="checkbox">
                    <?php echo $this->formCheckbox($filterForm->get($filter)->get($value)); ?> <?php echo $filterForm->get($filter)->get($value)->getLabel(); ?>
                    <button class="btn btn-mini disabled pull-right"><?php echo $filterForm->get($filter)->get($value)->getAttribute('data-hitNb'); ?></button>
                </label>
                <?php endforeach; ?>
            </div>
        </div>
        <?php endforeach; ?>
        <div class="filter-search">
            <h4><?php echo $this->translate('Questions'); ?></h4>
            <div class="filter-choice">
                <button class="min-slider btn btn-mini disabled pull-left"></button>
                <button class="max-slider btn btn-mini disabled pull-right"></button>
                <input id="questionNb" type="text" class="span12" value="" data-slider-min="0" data-slider-max="50" data-slider-step="1" data-slider-value="[0,50]" data-slider-selection="after" data-slider-tooltip="hide">  
            </div>
        </div>
        <div class="filter-search">
            <h4><?php echo $this->translate('Keywords'); ?></h4>
            <span id="keywords-bar" data-placeholder="<?php echo $this->translate('Enter a keyword'); ?>"></span>
        </div>
    </div>
    <div class="span9" id="search_results_body">
        <div class="row-fluid  well well-small" id="search_result_summary">
            <?php echo sprintf($this->translate('%s results'),count($lists)); ?>
        </div>
        <div class="row-fluid">
            <ul id="search_result_lists">
                
                <?php echo $this->listquestCollection($lists); ?>               
            </ul>
        </div>
        <div class="row-fluid" id="bottom_search_result_pagination_info">
            <div class="span6">
                <span id="search-results"></span>
            </div>
            <div class="span6" id="search_search-pagination"  class="pull-right"></div>
        </div>
    </div>
</div>
        