<?php

$title = $this->translate('Learn at LearnLists');
$this->headTitle($title);
$this->placeholder('header')->captureStart();
$searchForm->setAttribute('action', $this->url('lrnl-search'));
$searchForm->prepare();
?>

<div class="row-fluid search_bar_top">
    <div class="span12">
        <div class="row-fluid  well well-small">
            <?php echo $this->form()->openTag($searchForm);?>
            <?php echo $this->formRow($searchForm->get('search')); ?>
            <?php echo $this->formRow($searchForm->get('language')); ?>
            <button type="submit" class="btn btn-large btn-primary"><i class="icon-white icon-search"></i> <?php echo $this->translate('Search'); ?></button>
            <?php echo $this->form()->closeTag();?> 
        </div>
    </div>
</div>
<div class="row-fluid search_engine">
    <div class="span3">
        <div class="span11 well" id="left_side_filters">
            <?php foreach ($filterForm->getFieldsets() as $filter):  ?>
            <?php if ($filter->getAttribute('data-filterType') === 'checkbox'): ?>
            <div class="filter-search filter-search-term">
                <a type="button" data-toggle="collapse" data-target="#<?php $name = 'collapse'.$filter->getName();echo $name; ?>">
                    <h5 class="well"><?php echo ucfirst($this->translate($filter->getLabel())); ?></h5>
                </a>
                <div class="collapse in filter-choice" id="<?php echo $name; ?>">
                    <div class="well">
            <?php foreach ($filter->getElements() as $checkbox): 
                $checkbox->setAttribute('data-url',$this->url('lrnl-search',[],['query' => $checkbox->getQueryUrl()]));
                ?>
                        <label class="checkbox">
                            <?php echo $this->formCheckbox($checkbox); ?> <?php echo $checkbox->getLabel(); ?>
                            <span class="badge pull-right"><?php echo $checkbox->getAttribute('data-hitNb'); ?></span>
                        </label>
            <?php endforeach; ?>
                    </div>
                </div>
            </div>
            <?php endif;?>
            
            
            <?php if ($filter->getAttribute('data-filterType')==='range'): ?>
            <?php foreach ($filter->getElements() as $range): 
                $range->setAttribute('data-url',$this->url('lrnl-search',[],['query' => $range->getQueryUrl()]));
            ?>
            <div class="filter-search filter-search-range">
                <a type="button" data-toggle="collapse" data-target="#<?php $name = 'collapse'.$range->getName();echo $name; ?>">
                     <h5 class="well"><?php echo ucfirst($this->translate($range->getLabel())); ?></h5>
                </a>               
                <div class="collapse in filter-choice" id="<?php echo $name; ?>">
                    <div class="well">
                        <span class="min-slider label label-important pull-left"></span>
                        <span class="max-slider label label-important pull-right"></span>
                        <?php echo $this->formInput($range); ?>  
                    </div>
                </div>
            </div>
            <?php endforeach; ?>
            
            
            <?php endif;?>
            <?php if ($filter->getAttribute('data-filterType')==='search'): ?>
            <?php foreach ($filter->getElements() as $search): 
                $search->setAttribute('data-url',$this->url('lrnl-search',[],['query' => $search->getQueryUrl()]));            
            ?>
            <div class="filter-search filter-search-search">
                <a type="button" data-toggle="collapse" data-target="#<?php $name = 'collapse'.$search->getName();echo $name; ?>">
                    <h5 class="well"><?php echo $search->getLabel(); ?></h5>
                </a>
                <div class="collapse in filter-choice" id="<?php echo $name; ?>">
                    <div class="well input-append">
                        <?php echo $this->formInput($search); ?>
                        <button class="btn btn-primary">
                            <i class="icon icon-white icon-search"></i>
                        </button>
                    </div>
                </div>
            </div>
            <?php endforeach; ?>
            <?php endif;?>
            <?php endforeach; ?>
        </div>
    </div>
    <div class="span9" id="search_results_body">
        <div class="row-fluid  well well-small" id="search_result_summary">
            <?php echo sprintf($this->translate('%s results'),$resultNb); ?>
        </div>
        <hr>
        <div class="row-fluid">
            <div class="row-fluid">
               <ul id="search_result_lists">
                    <?php echo $this->listquestCollection($lists); ?>               
                </ul> 
            </div>
            <div class="row-fluid">
                <div class="span6">
                    <button id="comment-button" type="button" class="btn" data-toggle="collapse" data-target="#comment">
                        <i class="icon-comment"></i> <?php echo $this->translate('Leave a comment!') ?>
                    </button>
                </div>
                <div class="span6">
                    <?php echo $this->paginationControl($this->lists,'Sliding','pagination_control', ['route' => 'lrnl-search','query' => $query]); ?>
                </div>
            </div>
        </div>
    
    
        <div id="comment" class="collapse"><div id="disqus_thread"></div></div>
            <script type="text/javascript">
                 var disqus_developer = 1; // this would set it to developer mode
                /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
                var disqus_shortname = 'lrnl'; // required: replace example with your forum shortname

                /* * * DON'T EDIT BELOW THIS LINE * * */
                (function() {
                    var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
                    dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
                    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
                })();
            </script>
        <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
        <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
    </div>
</div>
        