<?php
use DluTwBootstrap\Form\FormUtil;

$formType = FormUtil::FORM_TYPE_VERTICAL;

$title = 'Change picture of a category';
$form->setAttribute('action', $this->url('lrnlcategory/editpicture', ['id' => $id]));
$form->prepare();
?>
<h3><?php echo $title; ?></h3>
<?php if ($form->getMessages()): ?>
<div class="alert alert-error">
    <button class="close" data-dismiss="alert" type="button">×</button>
    <strong><?php echo $this->translate('There were some errors. Please try again!'); ?></strong>
    <p><?php echo $this->formElementErrors($form); ?>
</div>
<?php endif; ?>
<?php echo $this->formTwb()->openTag($form); ?>
<?php echo $this->formCollection($form->get('category')); ?><br/>
<?php echo $this->formHidden($form->get('csrf')); ?>
<?php echo $this->formActionsTwb([$form->get('submit')],$formType);?>
<?php echo $this->formTwb()->closeTag($form); ?>