<?php
$title = $this->translate('Delete review');
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>

<p><?php echo $this->translate('Are you sure you want to delete the review'); ?>'?
</p>
<form action="<?php echo $this->url('vxoreview/delete', ['id' => $id]); ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int)$id; ?>" />
    <div class="form-actions">
        <input type="submit" name="del" value="Yes" />
        <input type="submit" name="del" value="No" />
    </div>
</div>
</form>