<?php
$title = $this->translate('Learn at LearnLists');
$this->headTitle($title);
?>
<article id="questionMain"></article>
<input name="id" type="hidden" data-comments='<?php echo $this->comments(); ?>' data-loggedin="<?php echo $this->zfcUserIdentity()? 'true' : 'false'; ?>" data-timePerQuestion="<?php echo $this->escapeHtml($timePerQuestion)?>" data-maxRound="<?php echo $this->escapeHtml($maxRound)?>" id="listId" value="<?php echo $listId ?>">
<script id="layout-template" type="text/html">
    <div class="row-fluid">
        <div class="span9">
            <div class="row-fluid" id="top-region"></div>
            <div class="row-fluid" id="main-region"></div>
        </div>
        <div class="span3" id="side-region"></div>
    </div>
</script>
<script id="top_region-template" type="text/html">    
    <div class="span8" id="left-top-region"></div>
    <div class="span2" id="center-top-region"></div>
    <div class="span2" id="right-top-region"></div>
</script>
<script id="main_region-template" type="text/html">
    <div class="well">
        <div class="row-fluid" id="question-region"></div>   
        <div class="row-fluid">
            <div class="span6" id="answer-region"></div>
            <div class="span6" id="comment-region"></div>
        </div>
    </div>
    <div class="row-fluid" id="input-region"></div>
    <div class="row-fluid">
        <div class="offset7 span5" id="main_buttons-region"></div>
    </div>
</script>    
<script id="side_region-template" type="text/html"> 
    <div data-step="10" data-intro="<? echo $this->translate('You have limited time to answer'); ?>" class="row-fluid" id="top-side-region"></div>
    <div class="row-fluid" id="middle_top-side-region"></div>
    <div class="row-fluid" id="middle-side-region"></div>
    <div class="row-fluid" id="bottom-side-region"></div>
</script>    

<script id="title_list-template" type="text/html">
    <h3 data-step="1" data-intro="<? echo $this->translate('The list you have choosen'); ?>"id="title_list"><%= title_list %></h3>
</script>    
<script id="round_number-template" type="text/html">
    <span data-step="8" data-intro="<? echo $this->translate('You can do several rounds of the same list, you will see how many you did already.This function is available only if your are logged in since it will save your progress and adapt the method of asking.'); ?>" class="label" ><?php echo $this->translate('Round'); ?> <%= round_nb %> / <%= round_total %></span>
</script>
<script id="timer-template" type="text/html">
    <input type="text" id="countdown">
    <div type="text" id="timer"></div>
</script>
<script id="question-template" type="text/html">   
    <div data-step="2" data-intro="<? echo $this->translate('Question you have to answer or containing missing element'); ?>" id="question_asked_text"><%= text %></div>
</script>
<script id="answer-template" type="text/html">
    <h4 id="answer_title" class="answer-region title" style="display:none"><?php echo $this->translate('Answer'); ?></h4>
    <p class="answer_text answer-region" style="display:none"><%= answer %></p>
</script>
<script id="comment-template" type="text/html">
    <h4 class="comment-region" style="display:none"><?php echo $this->translate('Comment'); ?></h4>
    <p id="tip_text" class="comment-region" style="display:none"><%= comment %></p>
</script>
<script id="input-template" type="text/html">
    <input name="id" type="hidden" id="listId" value="<?php echo $listId ?>">
    <span class="control-group" id="answer-group">
       <input data-step="3" data-intro="<? echo $this->translate('Submit your answer here. If there are several answers to give, please validate after each answer'); ?>" class="input-xxlarge" name="answer" type="text" id="question_asked_answer" placeholder="<?php echo $this->translate('Answer here'); ?>" autocomplete="off" value=""/>
    </span>
    </script>
<script id="main_buttons-template" type="text/html">
    <div class="well">
       <input data-step="4" data-intro="<? echo $this->translate('Then press the submit button (or press enter)'); ?>" name="submit" type="submit" id="question_asked_submitbutton" class="btn btn-large btn-success button-answer" value="<?php echo $this->translate('Check'); ?>"/>
        <a title="<?php echo $this->translate('Get the answer'); ?>" data-step="5" data-intro="<? echo $this->translate('Press this button if you want to see the answer. In this case you will get 0 points.'); ?>" id="question_asked_showanswerbutton" class="btn btn-danger btn-large button-answer">
            <i class="icon-lightbulb"/> 
        </a>
       <a title="<?php echo $this->translate('Skip'); ?>" data-step="6" data-intro="<? echo $this->translate('Press this button if you want to skip this question. You will be asked automatically later.'); ?>" id="question_asked_nextbutton" class="btn btn-large btn-primary button-answer" data-text-toggle="<?php echo $this->translate('Next'); ?>">
            <i class="icon-repeat icon-chevron-right"></i>
        </a>
    </div>
</script>
<script id="question_follower-template" type="text/html">
    <span data-step="7" data-intro="<? echo $this->translate('Number of question you have left to complete a round'); ?>" class="label label-important" >
            <?php echo $this->translate('Questions'); ?> <%= nb_question %> / <%= nb_questions %>
    </span>    
</script>
<script id="check_message-template" type="text/html">
    <div data-step="9" data-intro="<? echo $this->translate('Check if your answer is wrong or right and some comments according to your past results'); ?>" class="well">
        <h4 id="checkMessageTitle" class="checkMessage-view"><%= checkMessageTitle %></h4>
        <p id="newPoints" class="checkMessage-view"><span class="badge"><%= newPoints %></span></p>
        <p id="comments" class="checkMessage-view"><%= comments %></p>
    </div>
</script>
<script id="score-template" type="text/html">
    <div data-step="10" data-intro="<? echo $this->translate('Your score. Press on the help button to see how it is computed'); ?>" class="well">
        <h4><?php echo $this->translate('Score'); ?></h4>
        <h4><%= score %> (<?php echo sprintf($this->translate('max : %s'),'<%= maxPoint %>'); ?>)</h4>
    </div>
</script>
<script id="side_buttons-template" type="text/html">
    <div class="pull-right">
        <a  title="<?php echo $this->translate('Reset rounds'); ?>" href="#" style="display:none" id="remove_rounds_button" class="btn reset_button">
            <i class="icon-remove-circle icon-white"></i>
        </a>
        <a  title="<?php echo $this->translate('Cancel round'); ?>" href="#" id="question_asked_cancelRound" class="btn">
                <i class="icon-repeat"></i>
        </a>
        <a data-step="11" data-intro="<? echo $this->translate('You can reset the current round to a new round'); ?>" title ="<?php echo $this->translate('Again'); ?>" href="#" style="display:none" id="question_asked_resetbutton" class="btn reset_button">
            <i class="icon-repeat"></i>
        </a>
        <span data-step="12" data-intro="<? echo $this->translate('Get some help anytime'); ?>" class="dropdown">
            <a data-toggle="dropdown" title ="<?php echo $this->translate('Help'); ?>" class="dropdown-toggle btn help_button"><i class="icon-question-sign"></i></a>
            <ul class="dropdown-menu" role="menu">
                <li><a id="introjs_start_btn" ><?php echo $this->translate('How does it work?'); ?></a></li>
                <li><a data-toggle="modal" href="#score-help"><?php echo $this->translate('How is the score calculated?'); ?></a></li>
            </ul>
        </span>
    </div>
</script>
<script id="results-template" type="text/html">
    <h4><?php echo $this->translate('Score'); ?></h4>
    <h4><%= score %> (max : <%= maxPoint %> for <%= nb_questions %> questions)</h4>
    <table class="table" id="table_results">
        <thead id="head_table_results">
            <tr>
                <th><?php echo $this->translate('Round'); ?></th>
                <th><?php echo $this->translate('Score'); ?></th>
                <th><?php echo '4 '.$this->translatePlural('point','points',4); ?></th>
                <th><?php echo '3 '.$this->translatePlural('point','points',3); ?></th>
                <th><?php echo '2 '.$this->translatePlural('point','points',2); ?></th>
                <th><?php echo '1 '.$this->translatePlural('point','points',1); ?></th>
                <th><?php echo '0 '.$this->translatePlural('point','points',0); ?></th>
                <th><?php echo $this->translate('not done'); ?></th>
            </tr>
        </thead>
        <tbody id="body_table_results">
        </tbody>
    </table>
</script>
<script id="row_resultTable-template" type="text/html">
    <th><%= roundinfo() %></th>
    <th><%= finalnote %></th>
    <th><%= perfectanswer %></th>
    <th><%= averageplusanswer %></th>
    <th><%= averageanswer %></th>
    <th><%= averageminusanswer %></th>
    <th><%= badanswer %></th>            
    <th><%= notdone %></th>            
</script>

<script id="noresult-template" type="text/html">
    <p>
        <?php echo $this->zfcUserIdentity()? $this->translate('You did not yet finished one round!') : $this->translate('Please log In if you want to get more detailed results'); ?>
    </p>
</script>
<script id="loading-template" type="text/html">
    <div class="row-fluid">
        <div class="offset4 span4">
            <div class="well well-large well-transparent lead">
                <i class="icon-spinner icon-spin icon-2x pull-left"></i>
                <?php echo sprintf($this->translate('Loading your list <em>%s<em>'),''); ?>
            </div>
        </div>
    </div>
</script> 
<script id="empty-template" type="text/html"><span></span></script>
<!-- Modal -->
<div id="score-help" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel"> <?php echo $this->translate('How is your score calculated?'); ?></h3>
  </div>
  <div class="modal-body">
      <p> <?php echo $this->translate('The score depends on your ability to give the correct answer <strong>quickly</strong> and <strong>with no mistakes</strong>.'); ?>
      <p> <?php echo $this->translate('After each question you will receive :'); ?></p>
    <ul>
        <li>
            <?php echo $this->translate('+4 points if you answer correctly in the limited time'); ?>
        </li>
        <li>
             <?php echo $this->translate('+3 points if you answer correctly but overtime'); ?>
        </li>
        <li>
             <?php echo $this->translate('+2 points if you answer correctly after having given one wrong answer'); ?>
        </li>
        <li>
             <?php echo $this->translate('+1 points if you answer correctly after having given more than one wrong answer'); ?>
        </li>
        <li>
             <?php echo $this->translate('0 point if you have asked for the answer'); ?>
        </li>
    </ul>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true"> <?php $this->translate('Go back to learning'); ?></button>
  </div>
</div>
<!-- Modal -->
<div id="start-modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button id="close-welcome" type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Learnlists</h3>
  </div>
  <div class="modal-body">
    <p><?php echo $this->translate('You will soon start a new list, please take the time to understand how it works before using Learnlists. It takes 15 seconds!'); ?></p>
  </div>
  <div class="modal-footer">
    <button id="start-learn-btn" class="btn" data-dismiss="modal" aria-hidden="true"><?php echo $this->translate('Start learning directly'); ?></button>
    <button id="seeHowItWorks-btn" class="btn btn-primary"><?php echo $this->translate('Show starting guide'); ?></button>
  </div>
</div>