<?php

$this->headLink()   ->prependStylesheet($this->basePath() . '/css/vendor/bootstrap-progressbar.min.css');

$this->headScript() ->prependFile($this->basePath() . '/js/lib/marionette.min.js')
                    ->prependFile($this->basePath() . '/js/lib/backbone.min.js')
                    ->prependFile($this->basePath() . '/js/lib/underscore.min.js')
                    ->prependFile($this->basePath() . '/js/lib/jquery.knob.js')
                    ->prependFile($this->basePath() . '/js/lib/bootstrap-progressbar.min.js');

$this->inlineScript()->prependFile($this->basePath() . '/js/backboneMvc/View/CurrentStatsView.js')
                     ->prependFile($this->basePath() . '/js/backboneMvc/View/FollowerView.js')
                     ->prependFile($this->basePath() . '/js/backboneMvc/Model/Question.js')
                     ->prependFile($this->basePath() . '/js/backboneMvc/Model/Listquest.js')
                     ->prependFile($this->basePath() . '/js/backboneMvc/Model/Round.js')
                     ->prependFile($this->basePath() . '/js/backboneMvc/Model/Questionresult.js')
                     ->prependFile($this->basePath() . '/js/backboneMvc/Model/LearnMain.js')
                     ->prependFile($this->basePath() . '/js/backboneMvc/learnMVC.js');

$title = 'Learn at LearnLists';
$this->headTitle($title);?>
<article class="well" id="questionMain"></article>
<input name="id" type="hidden" data-loggedin="<?php echo $this->zfcUserIdentity()? 'true' : 'false'; ?>" data-maxRound="<?php echo $maxRound?>" id="listId" value="<?php echo $listId ?>">
<script id="layout-template" type="text/html">
    <div class="row-fluid">
        <h3 id="title_list"><%= title_list %></h3>
    </div>
    <div class="row-fluid">
        <div class="span9"> 
            <div class="row-fluid" id="central_area"></div>
            <div class="row-fluid" id="answer_show" style="display:none"></div>
            <div class="row-fluid" id="question_tip" style="display:none"></div>
            <div class="row-fluid" id="round-results" style="display:none"></div>
        </div>
        <div class="span3">
            <div class="row-fluid" id="question_follower"></div>
            <div class="row-fluid" id="first_presentation_corner"></div>
        </div>
    </div>
</script>
<script id="title_pie-template" type="text/html">
    <h4 id="round_show"><?php echo $this->translate('Round'); ?> <%= round_nb %> / <%= round_total %></h4>
    <div class="row-fluid pie">
        <input type="text" id="current_pie" class="pie">
    </div>
    <div class="row-fluid pie">
        <h3 class="pie title_pie" >
            <?php echo $this->translate('Still'); ?> <%= nb_question %>
        </h3>        
        <h4><?php echo $this->translate('Score:'); ?> <%= score %> / <%= maxPoint %></h4>
        <p><%= comments %></p>
    </div>
</script>
<script id="current_stats-template" type="text/html">
    <div class="progress bottom vertical progress-success">
        <div id="perfect_answering_bar"class="bar" data-percentage="<%= nb_perfect_answering %>"></div>
    </div>
    <div class="progress bottom vertical progress-warning">
        <div id="average_answering_bar"class="bar" data-percentage="<%= nb_average_answering %>"></div>
    </div>
    <div class="progress bottom vertical progress-danger">
        <div id="bad_answering_bar" class="bar" data-percentage="<%= nb_bad_answering %>"></div>
    </div>
</script>
<script id="results-template" type="text/html">
    <h3><?php echo $this->translate('Your results'); ?></h3>
    <table class="table" id="table_results">
        <thead id="head_table_results">
            <tr>
                <th><?php echo $this->translate('Round'); ?></th>
                <th><?php echo $this->translate('Final Note'); ?></th>
                <th><?php echo $this->translate('Perfect'); ?></th>
                <th><?php echo $this->translate('Average'); ?></th>
                <th><?php echo $this->translate('Bad'); ?></th>
                <th><?php echo $this->translate('Not done'); ?></th>
            </tr>
        </thead>
        <tbody id="body_table_results">
        </tbody>
    </table>
</script>
<script id="row_resultTable-template" type="text/html">
    <th><%= roundinfo() %></th>
    <th><%= finalnote %></th>
    <th><%= perfectanswer %></th>
    <th><%= averageanswer %></th>
    <th><%= badanswer %></th>            
    <th><%= notdone %></th>            
</script>
<script id="asking_question-template" type="text/html">    
    <p id="question_asked_text"><%= text %></p>            
    <form action="" method="post" name="questionAskForm" class="well well-small form-inline" id="questionAskForm">
        <input name="id" type="hidden" id="listId" value="<?php echo $listId ?>">        
        <span class="control-group" id="answer-group">
            <input class="input-xlarge" name="answer" type="text" id="question_asked_answer" placeholder="<?php echo $this->translate('Answer here'); ?>" autocomplete="off" value="klkm"/>
        </span>
        <input name="submit" type="submit" id="question_asked_submitbutton" class="btn btn-large btn-success button-answer" value="<?php echo $this->translate('Check'); ?>"/>
    </form>    
    <div class="row-fluid">
        <div class="offset8 span2">
          <a id="question_asked_nextbutton" class="btn btn-block btn-primary button-answer" data-text-toggle="<?php echo $this->translate('Next'); ?>"><?php echo $this->translate('Skip'); ?></a>
        </div>
        <div class="span2">
           <a id="question_asked_showanswerbutton" class="btn btn-danger btn-block button-answer"><?php echo $this->translate('Answer?'); ?></a>
        </div>
    </div>
</script>
<script id="answer_show-template" type="text/html">
    <h4 id="answer_title" class="title"><?php echo $this->translate('Answer'); ?></h4>
    <p class="answer_text"><%= answer %></p>
</script>
<script id="nav_bar_question-template" type="text/html">
    <a href="#" style="display:none" id="question_asked_resetbutton" class="btn btn-block btn-success reset_button">
            <i class="icon-repeat icon-white"></i> <?php echo $this->translate('Again'); ?>
    </a>
    <a href="#" id="question_asked_cancelRound" class="btn btn-block">
            <i class="icon-remove-sign"></i> <?php echo $this->translate('Cancel round'); ?>
    </a>
    <a href="#" style="display:none" id="remove_rounds_button" class="btn btn-block btn-danger reset_button">
            <i class="icon-remove-circle icon-white"></i> <?php echo $this->translate('Reset rounds'); ?>
    </a>
</script>
<script id="tip-template" type="text/html">
    <h4 class="tip"><?php echo $this->translate('Tip'); ?></h4>
    <p id="tip_text" class="tip"><%= tip %></p>
</script>
<script id="noresult-template" type="text/html">
    <p>Please log In if you want to get more detailed results</p>
</script>