<?php $this->headTitle()->prepend($this->translate('Contact')); ?>
<section class="contact">
<h2>Contact</h2>

<p>
    <?php echo $this->translate('This site is under test, please feel free to contact us to report any question, remark, suggestions...'); ?>
</p>

<?php if ($form->getMessages()):
?>
    <div class="alert alert-error">
        <button class="close" data-dismiss="alert" type="button">×</button>
        <strong><?php echo $this->translate('Try again, there were some mistakes...'); ?></strong>
    </div>
<?php
endif;
?>

<?php 
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url('contact/process'));
$form->setAttribute('method', 'post');
echo $this->form()->openTag($form);?>
<?php echo $this->formTwb($form, \DluTwBootstrap\Form\FormUtil::FORM_TYPE_VERTICAL,['elements' => ['Send' => ['class' => 'btn-primary']]]);?>
<?php echo $this->form()->closeTag() ?>
</section>
