<?php 
$title = $this->translate('Contact');
$this->headTitle()->prepend($title); 
$email = 'contact@learnquiz.voilamylife.com';
$link = '<a href="mailto:'.$email.'">';


?>
<section class="contact">
<h2><?php echo $title ; ?></h2>

<p>
    <?php echo $this->translate('This site is under test, please feel free to contact us to report any question, remark, suggestions...'); ?>
</p>
<p>
    <?php echo sprintf($this->translate('You can contact us directly at %s%s</a> or with the contact form:'),$link,$email); ?>
</p>

<?php if ($form->getMessages()):
?>
    <div class="alert alert-error">
        <button class="close" data-dismiss="alert" type="button">×</button>
        <strong><?php echo $this->translate('Try again, there were some mistakes...'); ?></strong>
    </div>
<?php
endif;
?>

<?php 
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url('contact/process'));
$form->setAttribute('method', 'post');
$form->get('from')->setLabel(_('From:'));
$form->get('subject')->setLabel(_('Subject:'));
$form->get('body')->setLabel(_('Your message:'));
$form->get('captcha')->setLabel(_('Please verify you are human.'));
$form->get('Send')->setValue(_('Send'));
echo $this->form()->openTag($form);?>
<?php echo $this->formTwb($form, \DluTwBootstrap\Form\FormUtil::FORM_TYPE_VERTICAL,['elements' => ['Send' => ['class' => 'btn-primary']]]);?>
<?php echo $this->form()->closeTag() ?>
</section>
