<?php 
$title = $this->translate('Error 404');
$this->headTitle($title);

$reasonMessage= '';
$controllerMessage='';
$additionalInfo='';
$previousExc='';

if (isset($this->reason) && $this->reason){
        switch ($this->reason) {
        case 'error-controller-cannot-dispatch':
            $reasonMessage = $this->translate('The requested controller was unable to dispatch the request.');
            break;
        case 'error-controller-not-found':
            $reasonMessage = $this->translate('The requested controller could not be mapped to an existing controller class.');
            break;
        case 'error-controller-invalid':
            $reasonMessage = $this->translate('The requested controller was not dispatchable.');
            break;
        case 'error-router-no-match':
            $reasonMessage = $this->translate('The requested URL could not be matched by routing.');
            break;
        default:
            $reasonMessage = $this->translate('We cannot determine at this time why a 404 was generated.');
            break;
    }
}

if (isset($this->controller) && $this->controller) {
    $controllerMessage = 'Controller '.$this->escapeHtml($this->controller);
        if (isset($this->controller_class)
        && $this->controller_class
        && $this->controller_class != $this->controller) {
            $controllerMessage .= sprintf($this->translate('resolves to %s'), $this->escapeHtml($this->controller_class));
        }
} 

if (isset($this->display_exceptions) && $this->display_exceptions) {
    if(isset($this->exception) && $this->exception instanceof Exception){
        
        $additionalInfo = 'Additional information :'
        .get_class($this->exception). 'File :'
        .$this->exception->getFile().'Line: '
        .$this->exception->getLine(). 'Message: '
        .$this->exception->getMessage().'Stack trace: '
        .$this->exception->getTraceAsString();
        
        if ($this->exception->getPrevious()){
            $previousExc = $this->exception->getPrevious();
                $previousException = 'Previous exception :';
            while($previousExc){
                $previousException .= get_class($previousExc). 'File :'
                .$previousExc->getFile().'Line: '
                .$previousExc->getLine(). 'Message: '
                .$previousExc->getMessage().'Stack trace: '
                .$previousExc->getTraceAsString();

                $previousExc = $previousExc->getPrevious();
            }
        }
    } else {
        $additionalInfo = 'No Exception available';
    } 
} ?>

<style>
  .center {text-align: center; margin-left: auto; margin-right: auto; margin-bottom: auto; margin-top: auto;}
</style>
<div class="hero-unit center">
    <h1><?php echo $this->message ?> <small><font face="Tahoma" color="red"><?php echo $this->translate('Error 404'); ?></font></small></h1>
    <br />
    <p>
        <?php echo $controllerMessage='';?><?php echo $additionalInfo='';?><?php echo $previousExc='';?>
    </p>
    <p><?php echo $reasonMessage ?> <?php echo $this->translate('The page you requested could not be found, either contact your webmaster or try again. Use your browsers <b>Back</b> button to navigate to the page you have prevously come from</p>
    <p><b>Or you could just press this neat little button:</b></p>'); ?>
    <a href="<?php echo $this->url('home'); ?>" class="btn btn-large btn-info"><i class="icon-home icon-white"></i> <?php echo $this->translate('Take Me Home'); ?></a>
</div>

    





