<?php

$title = 'Add new list';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php if (!$this->zfcUserIdentity()) : ?>

<p>Please log in in order to add a new list.</p>

<?php
else :
$form->setAttribute('action', $this->url('list', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('title'));
echo $this->formRow($form->get('tags')); 
echo $this->formRow($form->get('rules')); ?><br/>
<?php echo $this->formSubmit($form->get('submit')); ?>
<?php echo $this->form()->closeTag();?> 
<?php endif;?> 

