<?php

$title = 'Learn at LearnLists';
$this->headTitle($title);
$this->placeholder('header')->captureStart();
?>
<header id="jumbotron-header">
    <div class="container">
        <h1><?php echo $this->escapeHtml($title); ?></h1>
    </div>
</header>
<?php $this->placeholder('header')->captureEnd(); ?>
<table class="table">
    <thead>
        <tr>
            <th>#</th>
            <th>Category</th>
            <th>Title</th>
            <th>Questions</th>
            <th>Owner</th>
            <th>Date last contribution</th>
        </tr>
    </thead>
    <tbody>
<?php foreach ($lists as $list) : ?>
      <tr>
        <td><?php echo $list->id; ?></td>
        <td>category</td>
        <td><a href="<?php echo $this->url('question',['id' => $list->id]); ?>"><?php echo $list->title; ?></a></td>
        <td><?php echo count($list->questions); ?></td>
        <td><?php echo $this->gravatar($list->author->getEmail(),['img_size' => '30px']);echo ' '.$this->zfcUserDisplayName($list->author) ?></td>
        <td><?php echo $list->creationDate->format(\Zend\Stdlib\DateTime::W3C); ?></td>
      </tr>
<?php endforeach; ?>
    </tbody>
</table>