<?php
$title = $this->translate('Learn at LearnLists');
$this->headTitle($title);
$this->placeholder('header')->captureStart();
?>
<header id="jumbotron-header">
    <div class="container">
        <h1><?php echo $this->escapeHtml($title); ?></h1>
    </div>
</header>
<?php $this->placeholder('header')->captureEnd(); ?>
<h2>
    <a href="<?php echo $this->url('question',['id' => $list->id]); ?>"><?php echo $this->escapeHtml($list->title); ?></a> 
    (<?php $nbQuestion = count($list->questions); echo $nbQuestion.' '.$this->translatePlural('question','questions',$nbQuestion);?>)
<?php echo sprintf($this->translate('by %s created on %s'),
' '.$this->gravatar($list->author->getEmail(),['img_size' => '20px']).' '.$this->zfcUserDisplayName($list->author)
.' ('.$list->author->getRoles()[0]->getRoleId(). '), ', 
' '.$this->dateFormat($list->creationDate,IntlDateFormatter::MEDIUM)); ?>
    <a class="btn btn-primary pull-right" href="<?php echo $this->url('question',['action' => 'add','id' => $list->id]); ?>">
        <?php echo $this->translate('Add question'); ?>
    </a>
</h2>
<table class="table">
    <thead>
        <tr>
            <th></th>
            <th><?php echo $this->translate('Text'); ?></th>
            <th><?php echo $this->translate('Answer'); ?></th>
            <th><?php echo $this->translate('Tip'); ?></th>
        </tr>
    </thead>
    <tbody>
<?php foreach ($list->questions as $question) : ?>
    <tr>
        <td>
<?php if ($this->zfcUserIdentity() && ($list->author->getId() === $this->zfcUserIdentity()->getId())) :?> 
            <div class="btn-group">
                <a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#">
                  <?php echo $this->translate('Edit'); ?>
                  <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="<?php echo $this->url('question',['action' => 'edit','id' => $question->id]); ?>"><?php echo $this->translate('Edit'); ?></a></li>
                    <li><a href="<?php echo $this->url('question',['action' => 'delete','id' => $question->id]); ?>"><?php echo $this->translate('Delete'); ?></a></li>
                </ul>
           </div>
<?php else : ?>         
            <a class="btn btn-primary dropdown-toggle" href="#">
                <?php echo $this->translate('Add comment'); ?>                  
            </a>
<?php endif; ?>

        </td>
        <td><?php echo $question->text; ?></td>
        <td><?php echo $question->answer; ?></td>
        <td><?php echo $question->tip; ?></td>
    </tr>
<?php endforeach; ?>
    </tbody>
</table>