<?php
$title = $this->translate('Add new list');
$this->headTitle($title);

$form->setAttribute('action', $this->url('listquests/list/add'));
$form->prepare();
echo $this->form()->openTag($form);
$listquestFieldset = $form->get('listquest');
echo $this->formHidden($listquestFieldset->get('id'));
echo $this->formHidden($form->get('csrf'));
?>
<?php if ($form->getMessages()): ?>
<div class="alert alert-error">
    <button class="close" data-dismiss="alert" type="button">×</button>
    <strong><?php echo $this->translate('There were some errors. Please try again!'); ?></strong>
</div>
<?php endif; ?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<div class="row-fluid">
    <div class="span5">
        <?php echo $this->formRowTwb($listquestFieldset->get('title')); ?>
        <?php echo $this->formRowTwb($listquestFieldset->get('description')); ?>
        <?php echo $this->formRowTwb($listquestFieldset->get('language')); ?>
        <?php echo $this->formRowTwb($listquestFieldset->get('rules')); ?>
    </div>
    <div class="span5">
        <?php echo $this->formRowTwb($listquestFieldset->get('level')); ?>
        <?php echo $this->formFileTwb($listquestFieldset->get('category_picture')); ?><br/><br/>
        <?php echo $this->formRowTwb($listquestFieldset->get('category')); ?><br/>
        <div class="input-append">
            <span id="tags_element">
            <?php echo $this->formCollection($listquestFieldset->get('tags')); ?>
            </span>
            <button data-collection ="tags_element" class="btn add_item_to_collection_button" id="add_tags_button"><i class="icon-plus"></i></button>    
        </div>
    </div>
</div>
<div class="row-fluid">
    <div class="form-actions">
        <?php echo $this->formSubmit($form->get('submit')); ?>
    </div>
</div>
<?php echo $this->form()->closeTag($form);