<?php
$title = sprintf($this->translate('Edit %s'),$listquest->title);
$form->setAttribute('action', $this->url('listquests/list/edit', ['id' => $listquest->id]));
echo $this->partial('lrnl-listquests/listquest/save.phtml',[
    'title' => $title,
    'form' => $form,
    'tempFile' => $tempFile,
    'listquest' => $listquest
 ]);
?>
<div id="changePictureForm" class="modal hide fade">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3><?php echo $this->translate('Change your picture?'); ?></h3>
  </div>
  <div class="modal-body">
      <?php echo $this->formFile($this->formChangePicture()); ?>?>
  </div>
  <div class="modal-footer">
    <a href="#" class="btn">Close</a>
    <a href="#" class="btn btn-primary">Save changes</a>
  </div>
</div>