<?php
$title = sprintf($this->translate('Edit %s'),$listquest->title);
$form->setAttribute('action', $this->url('listquests/list/edit', ['id' => $listquest->id]));
echo $this->partial('lrnl-listquests/listquest/save.phtml',[
    'title' => $title,
    'form' => $form,
    'tempFile' => $tempFile,
    'listquest' => $listquest
 ]);
$urlChangePicture = $this->url('listquests/list/changepicture',['id' => $listquest->id]);
$changePictureForm->setAttribute('action', $urlChangePicture);
$changePictureForm->prepare();
?>
<div id="changePictureForm" class="modal hide fade">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3><?php echo $this->translate('Change your picture?'); ?></h3>
  </div>
  <?php echo $this->formTwb()->openTag($changePictureForm); ?>
  <div class="modal-body">
      <?php echo $this->formhiddenTwb($changePictureForm->get('csrf')); ?>
      <?php echo $this->formFileTwb($changePictureForm->get('listquest')->get('pictureId')); ?>
  </div>
  <div class="modal-footer">
    <?php echo $this->formSubmitTwb($changePictureForm->get('submit')); ?>
  </div>
   <?php echo $this->formTwb()->closeTag($changePictureForm);?>
</div>
<div id="questions_help_modal" class="modal hide fade">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3><?php echo $this->translate('How to write the content of a new question?'); ?></h3>
  </div>  
  <div class="modal-body">   
      <?php echo $this->partial('lrnl-help/help-static/create_new_question_content.phtml','LrnlHelp'); ?>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true"><?php echo $this->translate('Close'); ?></button>
  </div>   
</div>