<?php 
if (!isset($thumbLinesMax)){
    $thumbLinesMax = 2;
}
$thumbs = '';
$thumbLines = 0;
foreach ($lists as $list) { 
    $thumbs .=$this->cycle(['<div class="row-fluid"><ul class="thumbnails home">','','',''],'openTag')->next();
    $thumbs .=$this->listquestThumbnail($list);
    $thumbs .=$this->cycle(['','','','</ul></div>'],'closingTag')->next();
       
    $thumbLines += (string)$this->cycle([0,0,0,1],'nbLine')->next();
    if ($thumbLines === $thumbLinesMax){
        break;
    }
}
?>
<div class="row-fluid">
    <h3><?php echo $this->translate('Categories guide');?></h3>
    <h4><?php echo $this->translate('Here are some favourite categories you can choose from.'); ?></h4>
</div><br/>
<?php echo $thumbs;?>