<?php
$title = $this->translate('Learn with quizes');
$this->headTitle($title);
$this->headMeta()->appendName('description', $this->translate('Find the best quizes to learn what you wish from quizes prepared by our community of teachers or create your own quiz.'));

$site = $this->site();
$searchForm->get('search')->setAttribute('class','home '.$searchForm->get('search')->getAttribute('class'));

$features = [
    [
        'classWrap' => 'well span4',
        'title' => $this->translate('Find high quality quizes'),
        'text' => $this->translate('Quizes are developed by professional teachers and evaluated by the user commnunity which ensures top quality.'),
        'buttonUrl' => $this->url('lrnl-search'),
        'buttonText' => $this->translate('Explore quizes')
    ],
    [
        'classWrap' => 'well span4',
        'title' => $this->translate('Learn through efficient methods'),
        'text' => sprintf($this->translate('Thanks to teaching professionals (teachers and memory scientists and doctors), %s offers specific method that maximize the memorization processs and minimize the effort'),$site),
        'buttonUrl' => $this->url('lrnl-help/template',['template' => 'about_our_method']),
        'buttonText' => $this->translate('About our methods')
    ],
    [
        'classWrap' => 'well span4',
        'title' => $this->translate('Create and share quizes'),
        'text' => $this->translate('You can also create and share your own private quizes.'),
        'buttonUrl' => $this->url('lrnl-help/template',['template' => 'how_to_create_a_list']),
        'buttonText' => $this->translate('Learn how create quizes')
    ],
];

$dir = './module/Application/assets/images/homeslides/';
$dirLocale = '/assets/images/homeslides/';
$handler = opendir($dir);
$files=[];
// open directory and walk through the filenames
while ($file = readdir($handler)) {
    if (preg_match('#.*.(jpg|png|tif)$#',$file)){
        $files[] = $dirLocale.$file;
    }
}
$homeFiles = Zend\Json\Json::encode($files);

?>
<?php $this->placeholder('header')->captureStart();?>
<div class="backstretch" data-filebackstretch='<?php echo $homeFiles; ?>'>
    <header id="jumbotron-header" class="home">
        <div class="container">
            <div class="row">
                <h1><?php echo $this->escapeHtml($title); ?></h1>
                <h3><?php echo sprintf($this->translate('Learn with %d high quality quizes proposed by our community of teachers.'),count($lists),'x'); ?></h3>
            </div>
            <div class="row">
                <div class="well well-small ">
                    <?php echo $this->listSearchBar($searchForm); ?>
                </div>
            </div>
            <div class="row-fluid">
                <?php foreach ($lists as $list) : ?>
                <div class="offset9 span3 mini-line">
                    <?php echo $this->listquestCollection()->miniLine($list); ?>
                </div>
                <?php endforeach; ?>
            </div>
        </div>
    </header>
</div>
<?php $this->placeholder('header')->captureEnd(); ?>
<div class="thumb-line row-fluid">
    <div class="span12">
        <h2><?php echo $this->translate('Category guide');?></h3>
        <h4 class="muted"><?php echo $this->translate('Here are some favourite categories you can choose from.'); ?></h4>
        <?php echo $this->partial('lrnl-listquests/listquest/home/categoryThumbnails.phtml',['categories' => $categories,'thumbLinesMax' => 2]);?>
        <br/><br/><br/>
        <div class="row-fluid features">    
            <?php echo $this->partialLoop('lrnl-listquests/listquest/home/feature.phtml',$features); ?>
        </div>    
    </div>
</div>

    

