<?php
$title = $this->translate('Learn with quizzes');
$this->headTitle($title);

$searchForm->setAttribute('action', $this->url('lrnl-search'));
$searchForm->prepare();
$searchForm->get('search')->setAttribute('class','home '.$searchForm->get('search')->getAttribute('class'));

$features = [
    [
        'classWrap' => 'well span4',
        'title' => $this->translate('Find high quality quizzes'),
        'text' => $this->translate('Quizzes are developed by profesionnal teachers and evaluated by the user commnunity which ensures top quality.'),
        'buttonUrl' => $this->url('lrnl-search'),
        'buttonText' => $this->translate('Browse lists')
    ],
    [
        'classWrap' => 'well span4',
        'title' => $this->translate('Learn through efficient methods'),
        'text' => $this->translate('Thanks to teaching profesionnals (teachers and memory scientists and doctors), Learnlists offers specific method that maximize the memorization processs and minimize the effort'),
        'buttonUrl' => $this->url('lrnl-help/template',['template' => 'about_our_method']),
        'buttonText' => $this->translate('About our methods')
    ],
    [
        'classWrap' => 'well span4',
        'title' => $this->translate('Create and share quizzes'),
        'text' => $this->translate('You can also create and share your own private lists.'),
        'buttonUrl' => $this->url('lrnl-help/template',['template' => 'how_to_create_a_list']),
        'buttonText' => $this->translate('Learn how create lists')
    ],
];

?>
<?php $this->placeholder('header')->captureStart();?>
<div class="backstretch">
    <header id="jumbotron-header" class="home">
        <div class="container">
            <h1><?php echo $this->escapeHtml($title); ?></h1>
            <h3><?php echo sprintf($this->translate('Learn with %d high quality quizzes proposed by our community of teachers.'),count($lists),'x'); ?></h3>
            <div class="well well-small ">
                <?php echo $this->formTwb()->openTag($searchForm);?>
                <?php foreach ($searchForm as $element) : if ($element->getName() != 'submit') : ?>
                <?php echo $this->formRowTwb($element, \DluTwBootstrap\Form\FormUtil::FORM_TYPE_INLINE);?>
                <?php endif; endforeach; ?>
                <button type="submit" class="btn btn-large btn-primary"><i class="icon-white icon-search"></i> <?php echo $this->translate('Search'); ?></button>
                <?php echo $this->formTwb()->closeTag($searchForm);?> 
            </div>
        </div>
    </header>
</div>
<?php $this->placeholder('header')->captureEnd(); ?>
<div class="row-fluid">
    <h3><?php echo $this->translate('Quizz');?></h3>
    <h4><?php echo $this->translate('Here are some excellent quizz you can choose from.'); ?></h4>
</div><br/>
<?php echo $this->partial('lrnl-listquests/listquest/home/listquestThumbnails.phtml',['lists' => $lists,'thumbLinesMax' => 1]); ?>
<div class="row-fluid">
    <h3><?php echo $this->translate('Category guide');?></h3>
    <h4><?php echo $this->translate('Here are some favourite categories you can choose from.'); ?></h4>
</div><br/>
<?php echo $this->partial('lrnl-listquests/listquest/home/categoryThumbnails.phtml',['categories' => $categories,'thumbLinesMax' => 2]); ?>
<br/><br/>
<div class="row-fluid features">    
    <?php echo $this->partialLoop('lrnl-listquests/listquest/home/feature.phtml',$features); ?>
</div>
