<?php
$title = $this->translate('Learn with quizzes');
$this->headTitle($title);

$searchForm->setAttribute('action', $this->url('lrnl-search'));
$searchForm->prepare();
$searchForm->get('search')->setAttribute('class','home '.$searchForm->get('search')->getAttribute('class'));
?>
<?php $this->placeholder('header')->captureStart();?>
<header id="jumbotron-header" class="home">
    <div class="container">
        <h1><?php echo $this->escapeHtml($title); ?></h1>
        <h3><?php echo sprintf($this->translate('Learn with %d high quality quizzes proposed by our community of teachers.'),count($lists),'x'); ?></h3>
        <div class="well well-small ">
            <?php echo $this->form()->openTag($searchForm);?>
            <?php echo $this->formRow($searchForm->get('search')); ?>
            <?php echo $this->formRow($searchForm->get('language')); ?>
            <button type="submit" class="btn btn-large btn-primary home"><i class="icon-white icon-search"></i> <?php echo $this->translate('Search'); ?></button>
            <?php echo $this->form()->closeTag();?> 
        </div>
    </div>
</header>
<?php $this->placeholder('header')->captureEnd(); ?>
<div class="row-fluid">
    <div class="span4">
        <h2><?php echo $this->translate('Find high quality quizzes') ?></h2>
        <p><?php echo $this->translate('Quizzes are developed by profesionnal teachers and evaluated by the user commnunity which ensures top quality.'); ?></p>
        <p><a class="btn btn-success" href="<?php echo $this->url('listquests/list'); ?>"><?php echo $this->translate('Browse lists') ?> &raquo;</a></p>
    </div>

    <div class="span4">
        <h2><?php echo $this->translate('Learn through efficient methods') ?></h2>
        <p><?php echo $this->translate('Thanks to teaching profesionnals (teachers and memory scientists and doctors), Learnlists offers specific method that maximize the memorization processs and minimize the effort') ?></p>
        <p><a class="btn btn-success" href="<?php echo $this->url('listquests/list'); ?>"><?php echo $this->translate('About our methods') ?> &raquo;</a></p>
   </div>

   <div class="span4">
       <h2><?php echo $this->translate('Create and share quizzes') ?></h2>
       <p><?php echo $this->translate('You can also create and share your own private lists.'); ?></p>
       <p><a class="btn btn-success" href="<?php echo $this->url('listquests/list'); ?>"><?php echo $this->translate('Learn how create lists') ?> &raquo;</a></p>
   </div>
</div>
<!-- Button to trigger modal -->
<a href="#myModal" role="button" class="btn" data-toggle="modal">Launch demo modal</a>
 
<!-- Modal -->
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Modal header</h3>
  </div>
  <div class="modal-body">
    <p>One fine body…</p>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    <button class="btn btn-primary">Save changes</button>
  </div>
</div>
