<?php
$title = $this->translate('Sitemap');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<h2><?php echo $this->translate('Access directly any of our quizes:'); ?></h2>
<?php foreach ($lists as $list) : ?>
<p>
    <a href="<?php echo $this->url('learn/basic',['id' => $list->id,'title' => $this->strToUrl($list->title)]); ?>">
        <?php echo $this->escapeHtml($list->title); ?>
    </a>
</p>
<?php endforeach; ?>
