<?php
$this->headTitle($title);
$form->prepare();
$listquestFieldset = $form->get('listquest');
$tags = $listquestFieldset->get('tags');
if (isset($listquest)){    
    $imgUrl = $this->listquestPictureUrl($listquest);
    $imgAlt = ucfirst($this->escapeHtml($listquest->getTitle()));
} else {
    $listquest = NULL;
}

$questionsHelpUrl = '#questions_help_modal';
$form->get('listquest')->get('questions')->setLabel(sprintf($this->translate('Add questions (%sHow?</a>)'),'<a data-toggle="modal" href="'.$questionsHelpUrl.'">')); 

?>

<?php if ($form->getMessages()): ?>
<div class="alert alert-error">
    <button class="close" data-dismiss="alert" type="button">×</button>
    <strong><?php echo $this->translate('There were some errors. Please try again!'); ?></strong>
</div>
<?php endif; ?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php echo $this->form()->openTag($form); ?>
<?php echo $listquestFieldset->get('id') ?  $this->formHiddenTwb($listquestFieldset->get('id')) : ''?>
<?php echo $form->get('csrf') ? $this->formHiddenTwb($form->get('csrf')) : '' ?>
<div class="row-fluid">
    <div class="span5">
        <?php echo $this->formRowTwb($listquestFieldset->get('title')); ?>
        <?php echo $this->formRowTwb($listquestFieldset->get('description')); ?>
        <?php echo $this->formRowTwb($listquestFieldset->get('language')->get('id')); ?>
    </div>
    <div class="span5">
        <?php echo $this->formRowTwb($listquestFieldset->get('level')->get('id')); ?>
        <?php if ($listquest) : ?>
        <div class="picture_change">
            <p><?php echo sprintf($this->translate('%sChange</a> your current picture?'),'<a data-toggle="modal" href="#changePictureForm">'); ?></p>
            <?php echo $this->thumbnail(['src' => $imgUrl, 'alt' => $imgAlt], ['size' => 'medium']); ?>           
        </div>
         <?php endif;?>
        <?php if ($listquestFieldset->get('pictureId')) : ?>
        <?php echo $this->formLabelTwb($listquestFieldset->get('pictureId')); ?>
        <?php echo $this->formFileTwb($listquestFieldset->get('pictureId')); ?><br/>
        <?php echo $this->formElementErrors($listquestFieldset->get('pictureId')); ?><br/>
        <?php endif;?>
        <?php if ($tempFile) : ?>
        <div class="help-block">
            Uploaded: <?php echo $this->escapeHtml($tempFile['name']); ?>
        </div>
        <?php endif;?><br/>
        <?php echo $this->formRowTwb($listquestFieldset->get('category')->get('id')); ?><br/>
        <?php if ($tags) :?>
        <div class="input-append">
            <span id="tags_element">
            <?php echo $this->formLabelTwb($tags); ?>
            <?php echo $this->formCollection($tags->setLabel('')); ?>
            </span>
            <button data-collection ="tags_element" class="btn add_item_to_collection_button" id="add_tags_button"><i class="icon-plus"></i></button>    
        </div>
        <span class="help-inline">
            <?php foreach ($tags as $tag) : ?>
                <?php echo $this->formElementErrors($tag); ?>
            <?php endforeach; ?>
        </span>
        <?php endif; ?>
    </div>
</div>
<?php if ($listquestFieldset->get('questions')) : $questionTarget = $listquestFieldset->get('questions')->getTargetElement(); ?>
<div class="row-fluid collection">        
    <fieldset>
        <legend>
            <?php echo $this->form->get('listquest')->get('questions')->getLabel() ?>
        </legend>
    </fieldset>            
    <table>
        <thead <?php if (count($listquestFieldset->get('questions')) === 0) echo 'style="display:none"'; ?>>
            <th>
                <?php echo $questionTarget->get('text')->getLabel();?>
            </th>
            <th>
                <?php echo $questionTarget->get('answer')->getLabel();?>
            </th>
            <th><?php echo $questionTarget->get('comment')->getLabel();?></th>
            <th></th>
        </thead>
        <tbody>
            <?php foreach ($listquestFieldset->get('questions') as $question) : ?>        
        <tr class="populate">
            <?php echo $this->formHidden($question->get('id'));?>
            <td><?php echo $this->formInput($question->get('text'));?></td>
            <td><?php echo $this->formInput($question->get('answer'));?></td>
            <td><?php echo $this->formInput($question->get('comment'));?></td>
            <td class="btn-group">
                <div class="btn-group">
                    <a class="btn btn-mini btn-primary edit-question" data-questionId="<?php echo $question->get('id')->getValue(); ?>" href="<?php echo $this->url('listquests/question/edit',['id' => $question->get('id')->getValue()]); ?>" title="<?php echo $this->translate('Edit question'); ?>">
                        <i class="icon-edit icon-white"></i>
                    </a>
                    <a class="btn btn-mini btn-primary delete-question" data-questionId="<?php echo $question->get('id')->getValue(); ?>" href="<?php echo $this->url('listquests/question/delete',['id' => $question->get('id')->getValue()]); ?>" title="<?php echo $this->translate('Remove question'); ?>">
                        <i class="icon-remove icon-white"></i>
                    </a>
                </div>
            </td>
        </tr>  
        <?php endforeach;?>
        </tbody>
    </table>
    <div id="questions_element_adding">            
        <?php echo $this->formCollection()->renderTemplate($this->form->get('listquest')->get('questions')) ?>
        <div class="added_elements"></div>
        <a data-toggle="tooltip" data-placement="right" title="<?php echo $this->translate('Press to add a new empty line. To save press the button below'); ?>" data-collection="questions_element" class="btn add_item_to_collection_button"><i class="icon-plus"></i></a>
    </div>
</div>
<?php endif; ?>
<div class="row-fluid">
    <div class="form-actions">
        <?php echo $this->formSubmit($form->get('submit')); ?>
    </div>
</div>
<?php echo $this->form()->closeTag($form);