<?php 
$thumbnailAttribs = [
    'src' => $imgUrl,
    'alt' => $imgAlt,
    'title' => sprintf($this->translate('Quiz: %s'),$imgAlt),
    'style' => 'height:100px;'
];
$options = ['title' => $titleText];
if (isset($add)){
    $options['add'] = $add;
}        
?>

<li class="<?php echo $liClass; ?>">
    <a href="<?php echo $href; ?>"s>
        <?php echo $this->thumbnail($thumbnailAttribs, $options); ?>
    </a>
</li>