<?php
$title = $this->translate('Our Learning Offers');
$this->headTitle($title);
?>
<div class="well row-fluid">
    <div class="row-fluid">
        <h1 class="offers"><?php echo $this->translate('The quizzes that match your needs.'); ?></h1>
    </div>
    <div class="row-fluid">
        <div class="span4">
            <div class="offset2 well span10">
                <?php echo $this->priceCell(); ?>
            </div>
        </div>
        <div class="span4">
            <div class="offset1 well span10">
                <?php echo $this->priceCell(); ?>
            </div>
        </div>
        <div class="span4">
            <div class="well span10">
                <?php echo $this->priceCell(); ?>
            </div>
        </div>
    </div>
</div>