<?php 
$user = $this->zfcUserIdentity();
$authorRole = $author->getRoles()[0]->getRoleId();
$gravatar = $this->gravatar(
    $authorEmail,
    ['img_size' => '30px'],
    ['alt' => 'gravatar','title' => $this->zfcUserDisplayName($author)
        .' ('.$authorRole. ')']
);

$authorIsTeacher = ($authorRole === 'teacher');
$titleImage = sprintf($this->translate('Category %s'),$this->escapeHtml($category))
    .'-'.sprintf($this->translate('Quiz: %s'),$this->escapeHtml($title));

$pictureAttribs=[
    'src' => $urlImage,
    'title' => $titleImage,
    'alt' => $titleImage,
];

$urlLearn = $this->url('learn/basic',['id' => $id,'title' => $this->strToUrl($title)]);
$urlEdit = $this->url('listquests/list/edit',['id' => $id]);

$editAuthorized = $user && 
    ((($author->getId() === $user->getId()) 
        || ($user->getRoles()[0]->getRoleId() === 'admin')));
?>
<li class="search_result_listquest_item">
    <div class="row-fluid ">
        <div class="span2">            
             <?php echo $this->thumbnail($pictureAttribs, ['size' => 'small']); ?>
        </div>
        <div class="span10">
            <div class="row-fluid">
                <div class="span9">
                    <div class="title_with_icon">
                        <?php echo $gravatar ?>
                        <?php $htmlTag = ($questionNb != 0) ? 'a' : 'span'; ?>
                        <<?php echo $htmlTag; ?> href="<?php echo $urlLearn; ?>">
                            <h4 class="title_search_result_line">
                                <?php echo ucfirst($this->escapeHtml($title)); ?>
                                <?php if ($authorIsTeacher): ?>
                                <i title="<?php echo $this->translate('Teacher list'); ?>" class="icon-star-empty"></i>
                                <?php endif; ?>
                            </h4>
                        </<?php echo $htmlTag; ?>>
                    </div>
                    <p>
                        <?php echo $this->escapeHtml($description); ?>
                        <span class="muted date-listquest"><?php echo $this->dateFormat($creationDate,IntlDateFormatter::MEDIUM); ?></span>
                    </p>
                </div>
                <div class="span3 mainTopRight">
                    <?php if ($reviewNb) : ?>
                        <h2 class="text-right"><span class="rating"><?php echo $this->numberFormat(round($rating,1)); ?><span> / <small><?php echo $this->escapeHtml($ratingMax); ?></small></h2>
                        <p class="text-right"><small>(<?php echo $reviewNb;?> <?php echo $this->translatePlural('review','reviews',(int)$reviewNb); ?>)</small></p>
                    <?php else :?>
                        <h2 class="text-right"><small><?php echo $this->translate('Review it!'); ?></small></h2>
                    <?php endif;?>
                </div>
            </div>
            <div class="row-fluid">
                <div class="span9">
                    <span class="badge_item rating">
                        <span class="badge-bubble text_center">
                            <?php echo (int)$questionNb; ?>
                        </span>
                        <span class="muted title_badge">
                            <small>
                                <?php echo $this->translatePlural('question','questions',(int)$questionNb); ?>                                
                            </small>
                        </span>
                    </span>
                    <span class="badge_item level">
                        <span class="badge badge-level">
                            <?php echo ucfirst($this->translate($this->escapeHtml($level))); ?>
                        </span>
                        <span class="muted title_badge">
                            <small>
                                <?php echo $this->escapeHtml(ucfirst($this->translate('level')));?>
                            </small>
                        </span>
                    </span>
                    <span class="edit_button">
                        <?php if ($editAuthorized) :?> 
                                <a class="btn btn-mini btn-primary" href="<?php echo $urlEdit; ?>" title="<?php echo $this->translate('Edit list'); ?>">
                                    <i class="icon-edit icon-white"></i>
                                </a>
                        <?php endif; ?>
                    </span>
                </div>
                <div class="span3">
                    <?php if ($questionNb != 0) : ?>
                    <a href="<?php echo $urlLearn; ?>" class="btn btn-small btn-success pull-right btn-go">
                        <?php echo $this->translate('Start to learn');?>
                    </a>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
</li>
<hr>
      