<?php 
$user = $this->zfcUserIdentity();
$authorRole = $author->getRoles()[0]->getRoleId();
$gravatar = $this->gravatar(
    $authorEmail,
    ['img_size' => '30px'],
    ['alt' => 'gravatar','title' => $this->zfcUserDisplayName($author)
        .' ('.$authorRole. ')']
);

$authorIsTeacher = ($authorRole === 'teacher');
$titleImage = sprintf($this->translate('Category %s'),$this->escapeHtml($category))
    .'-'.sprintf($this->translate('Quizz: %s'),$this->escapeHtml($title));
$urlLearn = $this->url('learn/basic',['id' => $id,'title' => $this->strToUrl($title)]);
$urlEdit = $this->url('listquests/list/edit',['id' => $id]);
?>
<li class="search_result_listquest_item">
    <div class="row-fluid ">
        <div class="thumbnail span2">            
             <img src="<?php echo $urlImage; ?>" title="<?php echo $titleImage; ?>" alt="<?php echo $titleImage; ?>" style="height:70px;width:114px;">
        </div>
        <div class="span10">
            <div class="row-fluid">
                <div class="span10">
                    <div class="title_with_icon">
                        <?php echo $gravatar ?>
                        <?php $htmlTag = ($questionNb != 0) ? 'a' : 'span'; ?>
                        <<?php echo $htmlTag; ?> href="<?php echo $this->url('learn/basic',['id' => $id]); ?>">
                            <h4 class="title_search_result_line">
                                <?php echo ucfirst($this->escapeHtml($title)); ?>
                                <?php if ($authorIsTeacher): ?>
                                <i title="<?php echo $this->translate('Teacher list'); ?>" class="icon-star-empty"></i>
                                <?php endif; ?>
                            </h4>
                        </<?php echo $htmlTag; ?>>                     
                        <span class="edit_button">
                            <?php if ($user && ($author->getId() === $user->getId())) :?> 
                                    <a class="btn btn-mini btn-primary" href="<?php echo $urlEdit; ?>" title="<?php echo $this->translate('Edit list'); ?>">
                                        <i class="icon-edit icon-white"></i>
                                    </a>
                            <?php endif; ?>
                        </span>
                    </div>
                    <p>
                        <?php echo $this->escapeHtml($description); ?>
                        <span class="muted date-listquest"><?php echo $this->dateFormat($creationDate,IntlDateFormatter::MEDIUM); ?></span>
                    </p>
                </div>
                <div class="span2">
                    <h2 class="text-right questionNb"><?php echo (int)$questionNb; ?></h2>
                    <p class="text-right"><?php echo $this->translatePlural('question','questions',(int)$questionNb); ?></p>
                </div>
            </div>
            <div class="row-fluid">
                <div class="span9">
                    <?php foreach ([
                        ['name' => _('rating'),'value' => $rating,'class'=>'badge-bubble'],
                        ['name' => _('level'),'value' => $this->escapeHtml($level),'class'=>'badge badge-level']
                    ] as $badge) : ?>
                    <span class="badge_item">
                        <span class="<?php echo $this->escapeHtml($badge['class']); ?>">
                            <?php echo ucfirst($this->translate($this->escapeHtml($badge['value']))); ?>
                        </span>
                        <span class="muted title_badge">
                            <small>
                                <?php echo $this->escapeHtml(ucfirst($this->translate($badge['name'])));?>
                            </small>
                        </span>
                    </span>
                    <?php endforeach; ?>
                    <span class="like_button">
                        <?php if ($hasLike) : ?>                   
                        <span class="btn btn-mini disabled">
                            <i class="icon-thumbs-up"></i>                            
                        </span>
                        <span class="title_badge"><small><?php echo $this->translate('You like it');?></small></span>
                        <?php else : ?>
                        <a class="btn btn-mini" href="<?php echo $this->url('listquests/list/rate',['id' => $id]); ?>">
                            <i class="icon-thumbs-up"></i> <?php echo $this->translate('Yes');?>
                        </a>    
                        <?php endif;?>
                    </span>
                </div>
                <div class="span3">
                    <?php if ($questionNb != 0) : ?>
                    <a href="<?php echo $urlLearn; ?>" class="btn btn-small btn-success pull-right btn-go">
                        <?php echo $this->translate('Start to learn');?>
                    </a>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
</li>
<hr>
      