<?php

use DluTwBootstrap\Form\FormUtil;

$title = $this->translate('Sign In');
$this->headTitle($title);

$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login'));
$form->setAttribute('method', 'post');
$form->get('identity')->setLabel(_('Email or Username'));
$form->get('credential')->setLabel(_('Password'));
$form->get('submit')->setValue(_('Sign in'))->setLabel('');

$formType  = FormUtil::FORM_TYPE_VERTICAL;
$displayOptions = [
    'elements' => [
        'submit' => [
            'class' => 'btn-primary',
            'label' => false
        ],
    ],
];
?>
<h1><?php echo $this->translate('You have already an account') ?></h1>
<?php if ($form->getMessages()): ?>
<div class="alert alert-error">
    <button class="close" data-dismiss="alert" type="button">×</button>
    <strong><?php echo $this->translate('Try again!'); ?></strong>
</div>
<?php endif; ?>
<?php echo $this->form()->openTag($form) ?>
    <?php echo $this->formRowTwb($form->get('identity',$formType));?>
    <div class="control-group" id="cgroup-credential">
        <?php echo $this->formLabel($form->get('credential'));?>
        <div class="controls" id="controls-credential">
            <?php echo $this->formInput($form->get('credential'));?>
            <p>
                <a href="<?php echo $this->url('zfcuser/forgotpassword') ?>">
                    <?php echo $this->translate('Forgot your password?'); ?>
                </a>
            </p>
        </div>
    </div>
<?php if ($form->get('remember_me')) : $form->get('remember_me')->setLabel(_('Remember me on this computer'))?>
    <br/>
    <label class="checkbox">
        <?php echo $this->formCheckbox($form->get('remember_me')); ?> <?php echo $this->formLabel($form->get('remember_me')); ?>
    </label>
<?php endif; ?>
    <?php echo $this->formActionsTwb([$form->get('submit')], $formType, $displayOptions['elements']);?>
    <?php if ($this->redirect): ?>
    <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
    <?php endif ?>
<?php echo $this->form()->closeTag() ?>

