<?php

$this->headLink()   ->prependStylesheet($this->basePath() . '/css/vendor/bootstrap-progressbar.min.css');

$this->headScript() ->prependFile($this->basePath() . '/js/lib/marionette.min.js')
                    ->prependFile($this->basePath() . '/js/lib/backbone.min.js')
                    ->prependFile($this->basePath() . '/js/lib/underscore.min.js')
                    ->prependFile($this->basePath() . '/js/lib/jquery.knob.js')
                    ->prependFile($this->basePath() . '/js/lib/bootstrap-progressbar.min.js');

$this->inlineScript()->prependFile($this->basePath() . '/js/backboneMvc/View/QuestionView.js')
                     ->prependFile($this->basePath() . '/js/backboneMvc/View/CurrentStatsView.js')
                     ->prependFile($this->basePath() . '/js/backboneMvc/View/FollowerView.js')
                     ->prependFile($this->basePath() . '/js/backboneMvc/Model/Question.js')
                     ->prependFile($this->basePath() . '/js/backboneMvc/Model/Listquest.js')
                     ->prependFile($this->basePath() . '/js/backboneMvc/Model/Round.js')
                     ->prependFile($this->basePath() . '/js/backboneMvc/Model/Questionresult.js')
                     ->prependFile($this->basePath() . '/js/backboneMvc/Model/CurrentStats.js')
                     ->prependFile($this->basePath() . '/js/backboneMvc/utils/util.js')
                     ->prependFile($this->basePath() . '/js/backboneMvc/learnMVC.js');

$title = 'Learn at LearnLists';
$this->headTitle($title);
$this->placeholder('header')->captureStart();?>
<header id="jumbotron-header">
    <div class="container">
        <h1><?php echo $this->escapeHtml($title); ?></h1>
    </div>
</header>
<?php $this->placeholder('header')->captureEnd(); ?>
<article id="question">     
    <div class="row-fluid">
        <div class="span3">
            <div class="row-fluid">
                <div class="well sidebar-nav">
                    <ul class="nav nav-list">
                        <li class="nav-header">
                          <h4>
                              <span id="title-list"></span>                              
                          </h4>
                           <h5><?php echo $this->translate('Round'); ?> <span id="round-number"></span></h5>
                        </li>
                        <li>
                            <a href="#" style="display:none" id="question_asked_resetbutton" class="reset_button">
                                <i class="icon-repeat"></i> <?php echo $this->translate('Again'); ?>
                            </a>
                        </li>
                        <li>
                            <a href="#" id="question_asked_cancelRound" class="">
                                <i class="icon-remove-sign"></i> <?php echo $this->translate('Cancel round'); ?>
                            </a>
                        </li>
                        <li>
                            <a href="#" style="display:none" id="remove_rounds_button" class="reset_button">
                                <i class="icon-remove-circle"></i> <?php echo $this->translate('Reset rounds'); ?>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="row-fluid" id="question_follower"></div>
            <div class="well sidebar-nav">
                <ul class="nav nav-list">
                    <li class="nav-header">
                      <h4>
                          <?php echo $this->translate('Questions?'); ?>                             
                      </h4>
                    </li>
                    <li class="accordion-heading">
                        <a class="accordion-toggle" data-toggle="collapse" href="#general_rules">
                            <?php echo $this->translate('How does it work?'); ?>
                            <p class="accordion-body collapse" id="general_rules">soon</p>
                        </a>
                        <a class="accordion-toggle" data-toggle="collapse" href="#specific_rules">
                            <?php echo $this->translate('Special tips for this list'); ?>
                            <p class="accordion-body collapse" id="rules"></p>
                        </a>
                        <a class="accordion-toggle" data-toggle="collapse" href="#help_currentstats">
                            <?php echo $this->translate('How do the currentstats work?'); ?>
                            <p class="accordion-body collapse" id="help_currentstats">soon</p>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="span8"> 
            <div class="row-fluid" id="question-asking">        
                <div class=" span12 card well">
                    <p id="question_asked_text"></p>            
                    <form action="" method="post" name="questionAskForm" class="form-inline" id="questionAskForm">
                        <input name="id" type="hidden" id="listId" value="<?php echo $listId ?>">         
                        <div class="input-append input-prepend" id="input-answer-bar">
                            <span class="add-on">
                                <img id="check-sign" class="answer-sign" src="/images/icons/check.jpg" alt="check" hidden="true" style="max-height:17px;">
                                <img id="error-sign" class="answer-sign" src="/images/icons/error.jpg" alt="check" hidden="true" style="max-height:15px;">
                            </span>
                            <span class="control-group" id="answer-group">                
                                <input name="answer" type="text" id="question_asked_answer" placeholder="Answer" autocomplete="off" value="">
                            </span>
                            <input name="submit" type="submit" id="question_asked_submitbutton" class="btn btn-success button-answer" value="Check">
                            <button id="question_asked_nextbutton" class="btn btn-primary button-answer"><?php echo $this->translate('Next'); ?></button>    
                            <button id="question_asked_showanswerbutton" class="btn btn-danger button-answer"><?php echo $this->translate('Answer?'); ?></button>
                        </div>
                    </form>
                </div>
            </div>
            <div class="row-fluid" id="question_tip" style="display:none">
               <div class="span12 well"> 
                    <h4 class="tip" style="display:none"><?php echo $this->translate('Tip'); ?></h4>
                    <p id="tip_text" class="tip"></p>
                </div>        
            </div>
            <div class="row-fluid" id="round-results" style="display:none">  
                <div class="span12 well"> 
                    <h3><?php echo $this->translate('Your results'); ?></h3>
                    <table class="table">
                        <thead>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>  
            </div>
        </div>
        <div class="span1 well" id="current_stats"></div>  
    </div>
</article>

<script id="title_pie-template" type="text/html">
    <div class="row-fluid pie">
        <input type="text" id="current_pie" class="pie">
    </div>
    <div class="row-fluid pie">
        <p class="pie title_pie" >
            Still <%= nb_question %> question before the end of the round
        </p>
    </div>
</script>
<script id="current_stats-template" type="text/html">
    <div class="progress bottom vertical progress-success">
        <div id="perfect_answering_bar"class="bar" data-percentage="<%= nb_perfect_answering %>"></div>
    </div>
    <div class="progress bottom vertical progress-warning">
        <div id="average_answering_bar"class="bar" data-percentage="<%= nb_average_answering %>"></div>
    </div>
    <div class="progress bottom vertical progress-danger">
        <div id="bad_answering_bar" class="bar" data-percentage="<%= nb_bad_answering %>"></div>
    </div>
</script>
