<?php
$this->headScript() ->prependFile($this->basePath() . '/js/lib/marionette.min.js')
                    ->prependFile($this->basePath() . '/js/lib/backbone.min.js')
                    ->prependFile($this->basePath() . '/js/lib/underscore.min.js');

$this->inlineScript()->prependFile($this->basePath() . '/js/backboneMvc/View/QuestionView.js')
                     ->prependFile($this->basePath() . '/js/backboneMvc/Model/Question.js')
                     ->prependFile($this->basePath() . '/js/backboneMvc/Model/Listquest.js')
                     ->prependFile($this->basePath() . '/js/backboneMvc/Model/Round.js')
                     ->prependFile($this->basePath() . '/js/backboneMvc/Model/Questionresult.js')
                     ->prependFile($this->basePath() . '/js/backboneMvc/utils/util.js')
                     ->prependFile($this->basePath() . '/js/backboneMvc/learnMVC.js');

$title = 'Learn at LearnLists';
$this->headTitle($title);
$this->placeholder('header')->captureStart();?>
<header id="jumbotron-header">
    <div class="container">
        <h1><?php echo $this->escapeHtml($title); ?></h1>
    </div>
</header>
<?php $this->placeholder('header')->captureEnd(); ?>
<article id="question">     
    <div class="row-fluid">
        <div class="span3">
            <div class="row-fluid">
                <div class="well sidebar-nav">
                    <ul class="nav nav-list">
                      <li class="nav-header"><h4><span id="title-list"></span></h4></li>
                      <li class="active"><a href="#">Learn</a></li>
                      <li><a href="#"><?php echo $this->translate('Rules'); ?><p id="rules"></p></a></li>
                      <li>
                          <a href="#" style="display:none" id="question_asked_resetbutton" class="reset_button">
                              <i class="icon-repeat"></i> <?php echo $this->translate('Again'); ?>
                          </a>
                      </li>
                      <li>
                          <a href="#" id="question_asked_cancelRound" class=""><?php echo $this->translate('Cancel round'); ?></a>
                      </li>
                      <li>
                          <a href="#" style="display:none" id="remove_rounds_button" class="reset_button">
                              <?php echo $this->translate('Reset rounds'); ?>
                          </a>
                      </li>
                    </ul>
                </div><!--/.well -->
            </div>
            <div class="row-fluid">
                <div class="span12 card well">
                    <div class="row-fluid" id="results">
                        <div class="span6">
                            <img src="/images/check.jpg" alt="check" style="max-height:100px;">
                        </div>
                        <div class="span6">
                            <h3><span id="percent-firsttime">0</span>% <small>first time</small></h3>
                            <h4><span id="percent-noanswerused">0</span>% <small>found without answers</small></h4>                    

                        </div>
                    </div>
                    <div class="progress progress-info">
                        <div class="bar" style="width: 0%" id="bar-progress"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="span9"> 
            <div class="row-fluid" id="sub-title">        
                <div class=" span12 well">                    
                    <?php echo $this->translate('Round'); ?> <span id="round-number"></span>
                    Question X / <span id="nb-questions"></span>
                </div>
            </div>   
            <div class="row-fluid" id="question-asking">        
                <div class=" span12 card well">
                    <p id="question_asked_text"></p>            
                    <form action="" method="post" name="questionAskForm" class="form-inline" id="questionAskForm">
                        <input name="id" type="hidden" id="listId" value="<?php echo $listId ?>">         
                        <div class="input-append input-prepend" id="input-answer-bar">
                            <span class="add-on">
                                <img id="check-sign" class="answer-sign" src="/images/icons/check.jpg" alt="check" hidden="true" style="max-height:17px;">
                                <img id="error-sign" class="answer-sign" src="/images/icons/error.jpg" alt="check" hidden="true" style="max-height:15px;">
                            </span>
                            <span class="control-group" id="answer-group">                
                                <input name="answer" type="text" id="question_asked_answer" placeholder="Answer" autocomplete="off" value="">
                            </span>
                            <input name="submit" type="submit" id="question_asked_submitbutton" class="btn btn-success button-answer" value="Check">
                            <button id="question_asked_nextbutton" class="btn btn-primary button-answer"><?php echo $this->translate('Next'); ?></button>    
                            <button id="question_asked_showanswerbutton" class="btn btn-danger button-answer"><?php echo $this->translate('Answer?'); ?></button>
                        </div>
                    </form>
                </div>
            </div>
            <div class="row-fluid" id="question_tip" style="display:none">
               <div class="span12 well"> 
                    <h4 class="tip" style="display:none"><?php echo $this->translate('Tip'); ?></h4>
                    <p id="tip_text" class="tip"></p>
                </div>        
            </div>
            <div class="row-fluid" id="round-results" style="display:none">  
                <div class="span12 well"> 
                    <h3><?php echo $this->translate('Your results'); ?></h3>
                    <table class="table">
                        <thead>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>  
            </div>
        </div>
                
    </div>
</article>