<?php
$this->headScript() ->prependFile($this->basePath() . '/js/backbone.min.js')
                    ->prependFile($this->basePath() . '/js/underscore.min.js');

$this->inlineScript()->prependFile($this->basePath() . '/js/Question/startApp.js');
$this->inlineScript()->prependFile($this->basePath() . '/js/backboneMvc/View/QuestionView.js');
$this->inlineScript()->prependFile($this->basePath() . '/js/backboneMvc/Model/Question.js');
$this->inlineScript()->prependFile($this->basePath() . '/js/backboneMvc/Model/Listquest.js');
$this->inlineScript()->prependFile($this->basePath() . '/js/backboneMvc/utils/util.js');

$title = 'Learn at LearnLists';
$this->headTitle($title);
$this->placeholder('header')->captureStart();?>
<header id="jumbotron-header">
    <div class="container">
        <h1><?php echo $this->escapeHtml($title); ?></h1>
    </div>
</header>
<?php $this->placeholder('header')->captureEnd(); ?>
<article id="question">         
    <div class="row-fluid well" id="sub-title">        
        <h4><span id="title-list"></span> (<span id="nb-questions"></span> questions)</h4>   
        <button id="resetbutton" class="btn btn-warning"><i class="icon-repeat icon-white"></i> Again</button>
    </div>    
    <div class="row-fluid">
        <div class="offset1 span6 card well">
            <p id="text"></p>
    <?php        
    $form->prepare();
    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('id')->setValue($listId));
    ?>      
            <div class="input-append input-prepend" id="input-answer-bar">
                <span class="add-on">
                    <img id="check-sign" class="answer-sign" src="/images/icons/check.jpg" alt="check" hidden="true" style="max-height:17px;">
                    <img id="error-sign" class="answer-sign" src="/images/icons/error.jpg" alt="check" hidden="true" style="max-height:15px;">
                </span>
                <span class="control-group" id="answer-group">                
<?php echo $this->formRow($form->get('answer'));?>
                </span>
<?php echo $this->formSubmit($form->get('submit'));?>
                <button id="nextbutton" class="btn btn-primary button-answer">Next</button>    
                <button id="showanswerbutton" class="btn btn-danger button-answer">Answer?</button>      
<?php echo $this->form()->closeTag();?> 
            </div>
        </div>
        <div class="span4 card well">
            <div class="row-fluid" id="results">
                <div class="span6">
                    <img src="/images/check.jpg" alt="check" style="max-height:100px;">
                </div>
                <div class="span6">
                    <h3><span id="percent-firsttime">0</span>% <small>first time</small></h3>
                    <h4><span id="percent-noanswerused">0</span>% <small>found without answers</small></h4>                    
            
                </div>
            </div>
            <div class="progress progress-info">
                <div class="bar" style="width: 0%" id="bar-progress"></div>
            </div>
        </div>
    </div>
</article>