<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->site())->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
        <?php echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'])?>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top">
            
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="<?php echo $this->url('zfcadmin') ?>"><?php echo $this->site(); ?>Admin</a>
<?php echo $this->navigation('admin_navigation')
                            ->menu()
                            ->setUlClass('nav')
                            ->setMaxDepth(0)
                            ->setRenderInvisible(false)?>
                </div>
            </div>
        </nav>
        <?php echo $this->placeholder('header') ?>
        <div class="container">
            <?php echo $this->content; ?>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
