<?php
$this->selectLanguage()->setLabel($this->translate('Language: ').$this->language());
?>
<footer>
    <div class="row-fluid">
        <div class="offset1 span3">
            <h5><?php echo $this->site(); ?></h5>
            <ul>
                <li class="footer-item"><a href="<?php echo $this->url('home'); ?>"><?php echo $this->translate('Home'); ?></a></li>                
                <li class="footer-item"><a href="<?php echo $this->url('staticpages/template',['template' => 'features']); ?>"><?php echo $this->translate('Features'); ?></a></li> 
                <li class="footer-item"><a href="<?php echo $this->url('staticpages/template',['template' => 'about_our_method']); ?>"><?php echo $this->translate('Our methods'); ?></a></li> 
           </ul>
        </div>
        <div class="span3">
            <h5><?php echo $this->translate('Support'); ?></h5>
            <ul>
                <li class="footer-item"><a href="<?php echo $this->url('lrnl-help/template',['template' => 'welcome']); ?>"><?php echo $this->translate('Help center'); ?></a></li>
                <li class="footer-item"><a href="<?php echo $this->url('staticpages/template',['template' => 'terms_imprint']); ?>"><?php echo $this->translate('Terms and imprint'); ?></a></li>
                <li class="footer-item"><a href="<?php echo $this->url('contact'); ?>"><?php echo $this->translate('Contact us'); ?></a></li>    
                <li class="footer-item"><a href="<?php echo $this->url('staticpages/template',['template' => 'about']); ?>"><?php echo $this->translate('About us'); ?></a></li>
                <li class="footer-item"><a href="<?php echo $this->url('listquests/list/map'); ?>"><?php echo $this->translate('Sitemap'); ?></a></li>
            </ul>
       </div>
       <div class="offset2 span3">
           <?php echo $this->selectLanguage(); ?>
       </div>
    </div>
    <br/>
    <div class="row-fluid"> 
        <p class="text-center" id="copyright">
            <small>&copy; <?php echo $this->translate('2013 by Voilamylife.') ?> <?php echo $this->translate('All rights reserved.') ?></small>
        </p>
    </div>
    <div id="loadingPopup" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-body text-center">
            <h2 class="text-center">
                <div id="loading-icon"></div>
                <?php echo $this->translate('Loading...') ?>
            </h2>
        </div>
    </div>
</footer>