<?php
$helpNavigation = $this->navigation('help_center_navigation')->menu()->setPartial([
    'lrnl-help/help-static/sidenavbar.phtml','LrnlHelp']
)->render();
$siteName = $this->site();
?>
<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php $this->headTitle($siteName)->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
        <?php $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'])?>
        
        <?php
// for asset manager  assetic
            echo $this->plugin('HeadTitle');
            echo $this->plugin('HeadMeta');
            echo $this->plugin('HeadLink');
            echo $this->plugin('HeadStyle');
            echo $this->plugin('HeadScript');
        ?>
    </head>
    <body>
        <?php echo $this->header; ?>
        <?php echo $this->placeholder('header') ?>
        <div id="main" class="container">
            <h1><?php echo $this->translate('Help center'); ?></h1>
            <div class="row-fluid">                
                <div class="well span3">    
                    <?php echo $helpNavigation; ?>
                </div>
                <div class="span9">
                    <?php echo $this->content; ?>
                </div>
            </div>
            <br/><br/>
            <?php echo $this->footer; ?>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
