<?php
$siteName = $this->site();
$this->headTitle($siteName)->setSeparator(' - ')->setAutoEscape(false);
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');
$this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/assets/application/images/logo/favicon.ico']);
?>
<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php 
            echo $this->headTitle();
            echo $this->headMeta();
            echo $this->headLink();
            echo $this->headStyle();
            echo $this->headScript();
        ?>
    </head>
    <body>        
        <?php echo $this->header; ?>
        <?php echo $this->placeholder('header') ?>
        <div id="main" class="container">
            <?php echo $this->content; ?>
            <br/><br/>
            <?php echo $this->footer; ?>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
