<?php 
if ($this->zfcUserIdentity()) {
        $this->container->findById('profile')->setLabel(
        '<span id="gravatar-link">'
        .$this->gravatar($this->zfcUserIdentity()->getEmail(),['img_size' => '30px'])
        .'</span><span class="name">'.$this->zfcUserDisplayName().' (' 
        . $this->translate($this->zfcUserIdentity()->getRoles()[0]->getRoleId()). ')</span>'
    );
}?>
<div class="nav-collapse collapse">
    <?php echo $this->navigation()->menu()->renderMenu($this->container->findById('general'),['ulClass' => 'nav']);?>    
    <?php echo $this->navigation()->menu()->escapeLabels(false)->renderMenu($this->container->findById('user'),['ulClass' => 'nav pull-right']);?>
</div><!--/.nav-collapse -->