<?php
$title = $this->translate('About our methods');
$this->headTitle($title);
?>
<h1><?php echo $title; ?></h1>
<p>
    <?php echo $this->translate('Our methods for learning have been developed in order to be as efficient and sustainable as possible. They rely on following key principles:'); ?> 
</p>
<ul>
    <li>
        <?php echo $this->translate('Forget and remember : the repetition is one of the best way to learn'); ?>
    </li>
    <li>
        <?php echo $this->translate('Create link with other experience: repeat should be always different and always linked to other repetitions.'); ?>
    </li>
    <li>
        <?php echo $this->translate('Create feeling and pleasure: serious games helps also significantly to improve the way we remember.'); ?>
    </li>
</ul>

