<?php
$title = $this->translate('Add a new question');
$this->headTitle($title);

$createAListLink = '<a href="'.$this->url('lrnl-help/template',['template' => 'how_to_create_a_list']).'">';

$createListSteps = [
    [
        'number' => 1,
        'iconName' => 'signin',
        'title' => $this->translate('Sign in!'),
        'text' => $this->translate('To be able to create a new quiz or edit you own quizes you have to be identified!'),
    ],
    [
        'number' => 2,
        'iconName' => 'file-alt',
        'title' => $this->translate('I create a new quiz or I choose to edit one of my quizes'),
        'text' => sprintf($this->translate('You can %screate a quiz</a> or select one of your quizes to add new questions. In the browse quiz page, you will see an icon edit indicating you can edit and add questions to your quiz. Please note that you cannot add questions in other quizes than yours. '),$createAListLink),
    ],
    [
        'number' => 3,
        'iconName' => 'plus-sign',
        'title' => $this->translate('I write the content'),
        'text' => $this->partial('lrnl-help/help-static/create_new_question_content'),
    ],
    [
        'number' => 4,
        'iconName' => 'trophy',
        'title' => $this->translate('I can check that my question is now in my quiz'),
        'text' => $this->translate('The question will be automatically added after pushing on the save button. You can at anytime modify or remove any question.'),
    ],
];
?>
<p><?php echo $this->translate('To add a new question to a quiz, here are the steps you have to complete.'); ?></p>        
<ul class="unstyled">
    <?php echo $this->partialLoop('lrnl-help/help-static/step.phtml',$createListSteps); ?>
</ul>  
