<?php
$questionExample1 = new LrnlListquests\Form\Fieldset\QuestionFieldset('question1');
$questionExample1->get('id')->setValue(1);
$questionExample1->get('text')->setValue($this->translate('I cannot %put% up with him.'))->setAttribute('class','input-large');
$questionExample1->get('answer')->setValue('');
$questionExample1->get('comment')->setValue($this->translate('Some comments'))->setAttribute('class','input-medium');
$questionExample2 = new LrnlListquests\Form\Fieldset\QuestionFieldset('question1');
$questionExample2->get('id')->setValue(1);
$questionExample2->get('text')->setValue($this->translate('I %have% already %come% back from Scotland.'))->setAttribute('class','input-large');
$questionExample2->get('answer')->setValue('');
$questionExample2->get('comment')->setValue($this->translate('Some comments'))->setAttribute('class','input-medium');
$questionExample3 = new LrnlListquests\Form\Fieldset\QuestionFieldset('question1');
$questionExample3->get('id')->setValue(1);
$questionExample3->get('text')->setValue($this->translate('I cannot %stand--bear% this.'))->setAttribute('class','input-large');
$questionExample3->get('answer')->setValue('');
$questionExample3->get('comment')->setValue($this->translate('Some comments'))->setAttribute('class','input-medium');
$questionExample4 = new LrnlListquests\Form\Fieldset\QuestionFieldset('question1');
$questionExample4->get('id')->setValue(1);
$questionExample4->get('text')->setValue($this->translate('What is the capital of France ?'))->setAttribute('class','input-large');
$questionExample4->get('answer')->setValue($this->translate('Paris'));
$questionExample4->get('comment')->setValue($this->translate('Some comments'))->setAttribute('class','input-medium');

$writeQuestion = [
    sprintf($this->translate('Add a new question line by pushing %s, a line with 3 empty boxes will appear for the text of the question, the answer and comments'),'<a class="btn btn-mini"><i class="icon-plus"></i></a>'),
    $this->translate('Here are examples how to fill in text and answers. There are 2 possibilities: ')
        .$this->htmlList([
            $this->translate('<strong>question with one or more missing elements</strong>'). $this->htmlList([
                    $this->translate('simple example with one missing word: <em>I cannot (put) up with him</em>. In this case you must type the missing word (<em>put</em>) directly into the text and use the <em>%</em> sign:')
                        .$this->questionsFieldset([$questionExample1],false),
                    $this->translate('example with two missing words : <em>I ... already come ... from Scotland.</em>. As if the first example just type the missing words directly into the text and using the <em>%</em> sign:')
                        .$this->questionsFieldset([$questionExample2],false),
                    $this->translate('example with one missing word and two possible answers: <em>I cannot ... this situation anymore!</em>. To add several possibilities for one missing word add a double hyphen <em>--</em>:')
                        .$this->questionsFieldset([$questionExample3],false),
                ],false,false,false),    
            $this->translate('<strong>question with question mark</strong>. In this case just type the text and answer of the question:')
                    .$this->questionsFieldset([$questionExample4],false)
        ],
    false,false,false),
];
if ($this->hasRole('admin') || $this->hasRole('teacher')){
$writeQuestion[] = $this->partial('lrnl-help/help-static/write_comments');         
}
?>
<p><?php echo $this->translate('For each new each question: '); ?><p>
    <?php echo $this->htmlList($writeQuestion,false,false,false); ?>