<?php

$writeQuestion = [
    $this->translate('Add a new question line by pushing on the <em>plus button</em>.'),
    $this->translate('Add the <strong>text</strong> of the question. You can add two types of questions : ')
        .$this->htmlList([
            $this->translate('question with one or more missing elements'). $this->htmlList([
                    $this->translate('simple example with one missing word: <em>I cannot ... up with him</em>. In this case you must type the missing word(s) directly into the text and use the % sign to signal this is the answer: <code>I cannot %put% up with him.</code>'),
                    $this->translate('example with two missing words : <em>I ... already come ... from Scotland.</em>. As if the first example just type the missing word(s) directly into the text and using the % sign: <code>I %have% already %come% back from Scotland.</code>'),
                    $this->translate('example with one missing word and two possibilities: <em>I cannot ... this situation anymore!</em>. To add several possibilities for one missing word add a double hyphen <em>--</em>: <code>I cannot %stand--bear% this situation anymore.</code>'),
                ],false,false,false).    
            $this->translate('question with question mark, for example: <em>what is the most probable: I might go to the cinema or I may go to the cinema?</em> In this case just type the text of the question: <code>What is the most probable: I might go to the cinema or I may go to the cinema?</code>')],
    false,false,false),
    $this->translate('Add the <strong>answer</strong> of the question : there will be no answer in the case of a question with missing word(s).')
];
if ($this->hasRole('teacher')){
$writeQuestion[] = $this->partial('lrnl-help/help-static/write_comments');         
}
?>
<p><?php echo $this->translate('Follow the following steps to add and define the content of each question: '); ?><p>
    <?php echo $this->htmlList($writeQuestion,false,false,false); 
   

