<?php
$title = $this->translate('FAQ');
$this->headTitle($title);
$this->headTitle($this->translate('learner'));
?>
<ol>
    <li>
        <h4><?php echo $this->translate('How can I find the quiz with the best questions?'); ?></h4>
        <p><?php echo $this->translate('Our goal is to provide the best quizes to the learners. The search engine enables to search though the quizes prepared only by teachers in order to ensure their quality. Moreover every quiz is rated by its users so that you can easily identify the best quizes.'); ?></p>
    </li>
    <li>
        <h4><?php echo $this->translate('What is a round?') ?></h4>
        <p><?php echo $this->translate('A round consists of answering to all the question of a quiz. We consider that repeating several rounds allow to learn efficiently.') ?></p>
    </li>
</ol>

