<?php
$title = $this->translate('How to create a list');
$this->headTitle($title);

$recommendationLink = '<a href="'.$this->url('lrnl-help/template',['template' => 'recommendations_list']).'">';
$addNewQuestionLink = '<a href="'.$this->url('lrnl-help/template',['template' => 'add_new_question']).'">';
$createListSteps = [
    [
        'number' => 1,
        'iconName' => 'file-alt',
        'title' => _('I prepare my lists'),
        'text' => sprintf(_('Preparing the lists requires your time and talent. Please take a look on our %srecommendations</a> to enjoy the best experience for you and your lerners'),$recommendationLink),
    ],
    [
        'number' => 2,
        'iconName' => 'edit',
        'title' => _('I create a new container list'),
        'text' => _('When you create a new empty list, you will have to carefully choose its name and description. This is how your list will be identified from the user and your lerners. It is very important add a maximum of tags in order to facilitate to find you quizz.'),
    ],
    [
        'number' => 3,
        'iconName' => 'plus-sign',
        'title' => _('I add questions to the list'),
        'text' => sprintf(_('In order to save you time and give you a maximum of flexibility you can enter several questions at the same time, erase or modify any of the questions. Please read the %sadd a new question</a> section for a more detailed information.'),$addNewQuestionLink),
    ],
    [
        'number' => 4,
        'iconName' => 'trophy',
        'title' => _('I can check that my list has been published'),
        'text' => _('Automatically the list will be published and available when browsing the different lists.'),
    ],
];
?>
<p><?php echo $this->translate('To create a list, here are the steps you have to complete.'); ?></p>        
<ul class="unstyled">
    <?php echo $this->partialLoop('lrnl-help/help-static/step.phtml',$createListSteps); ?>
</ul>  
