<?php
$title = $this->translate('How to learn');
$this->headTitle($title);

$learnerSteps = [
    [
        'number' => 1,
        'iconName' => 'search',
        'title' => $this->translate('I find the quiz I want to learn from'),
        'text' => $this->translate('Go to "browse" in the navigation bar and choose a list from more than '
                . $this->listquestCount()
                .' lists. If you want to be sure of the quality, you can select quiz from teachers. There are indicated with the icon <i class="icon-star-empty"></i>.'),
    ],
    [
        'number' => 2,
        'iconName' => 'desktop',
        'title' => $this->translate('I answer to the questions'),
        'text' => $this->translate('Learn easily through answering to questions. After each question, you know how many points you won in the current round. You can obtain more help on how the learnlists tool for learning work directly on the page.'),
    ],
    [
        'number' => 3,
        'iconName' => 'bar-chart',
        'title' => $this->translate('I can immediately see my results'),
        'text' => $this->translate('After you have completed a round, you can see you results and compare with previous rounds (you have to be logged in).'),
    ],
    [
        'number' => 4,
        'iconName' => 'refresh',
        'title' => $this->translate('I repeat to consolidate and perform sustainable learning'),
        'text' => $this->translate('After each round, Learlists analyses and saves your results in order to optimize the questions the next time you decide to do the quiz. Basically through optimized repetition you can learn in the best way.'),
    ],
    [
        'number' => 5,
        'iconName' => 'trophy',
        'title' => $this->translate('I know it now'),
        'text' => $this->translate('Once you repeated several times the round, you can see how successfully you will reach a maximum point and reach you target to learn.'),
    ],
];

?>
<p><?php echo $this->translate('In order to learn, here are the steps you have to complete.'); ?></p>
<ul class="unstyled">
 <?php echo $this->partialLoop('lrnl-help/help-static/step.phtml',$learnerSteps); ?>
</ul>