<?php
$title = $this->translate('How does it work?');
$this->headTitle($title);
$this->headTitle($this->translate('learner'));

$learnerSteps = [
    [
        'number' => 1,
        'iconName' => 'search',
        'title' => _('I find the quizz I want to learn from'),
        'text' => _('Go to "browse" in the navigation bar and choose a list from more than '
                . $this->listquestCount()
                .' lists. If you want to be sure of the quality, you can select quizz from teachers. There are indicated with the icon <i class="icon-star-empty"></i>.'),
    ],
    [
        'number' => 2,
        'iconName' => 'desktop',
        'title' => _('I answer to the questions'),
        'text' => _('Learn easily through answering to questions. After each question, you know how many points you won in the current round. You can obtain more help on how the learnlists tool for learning work directly on the page.'),
    ],
    [
        'number' => 3,
        'iconName' => 'bar-chart',
        'title' => _('I can immediately see my results'),
        'text' => _('After you have completed a round, you can see you results and compare with previous rounds (you have to be logged in).'),
    ],
    [
        'number' => 4,
        'iconName' => 'refresh',
        'title' => _('I repeat to consolidate and perform sustainable learning'),
        'text' => _('After each round, Learlists analyses and saves your results in order to optimize the questions the next time you decide to do the quizz. Basically through optimized repetition you can learn in the best way.'),
    ],
    [
        'number' => 5,
        'iconName' => 'trophy',
        'title' => _('I know it now'),
        'text' => _('Once you repeated several times the round, you can see how successfully you will reach a maximum point and reach you target to learn.'),
    ],
];

?>
<h1><?php echo $this->translate('Find the best quizz to learn'); ?></h1>
<br/>
<ul class="nav nav-tabs">
  <li class="active">
      <a href="#learn" data-toggle="tab"><?php echo $this->translate('I want to learn'); ?></a>
  </li>
  <li>
    <a href="#create_list" data-toggle="tab"><?php echo $this->translate('I want to create my own list'); ?></a>
  </li>
</ul>

<div id="myTabContent" class="tab-content">
    <div class="tab-pane fade in active" id="learn">
        <p><?php echo $this->translate('In order to learn, here are the steps you have to complete.'); ?></p>
        <ul>
            <?php echo $this->partialLoop('lrnl-help/help-static/step.phtml',$learnerSteps); ?>
        </ul>
        
    </div>
    <div class="tab-pane fade" id="create_list">
      <?php echo $this->partial('lrnl-help/help-static/how_to_create_a_list.phtml'); ?>
    </div>    
</div>


