<?php
$title = $this->translate('How is the score calculated?');
$this->headTitle($title);
?>
<p> 
    <?php echo $this->translate('The score depends on your ability to give the correct answer <strong>quickly</strong> and <strong>with no mistakes</strong>.'); ?>
</p>    
<p> <?php echo $this->translate('After each question you will receive :'); ?></p>
<ul>
    <li>
        <?php echo $this->translate('+4 points if you answered correctly within the limited time'); ?>
    </li>
    <li>
         <?php echo $this->translate('+3 points if you answered correctly but overtime'); ?>
    </li>
    <li>
         <?php echo $this->translate('+2 points if you answered correctly after one wrong answer'); ?>
    </li>
    <li>
         <?php echo $this->translate('+1 point if you answered correctly after several wrong answers'); ?>
    </li>
    <li>
         <?php echo $this->translate('0 points if you have asked for the answer'); ?>
    </li>
</ul>