<?php
$title = $this->translate('How to create a quiz');
$this->headTitle($title);

$recommendationLink = '<a href="'.$this->url('lrnl-help/template',['template' => 'recommendations_list']).'">';
$addNewQuestionLink = '<a href="'.$this->url('lrnl-help/template',['template' => 'add_new_question']).'">';
$createListSteps = [
    [
        'number' => 1,
        'iconName' => 'file-alt',
        'title' => $this->translate('I prepare my quiz'),
        'text' => sprintf($this->translate('Preparing the quiz requires your time and talent. Please take a look on our %srecommendations</a> to enjoy the best experience for you and your learners'),$recommendationLink),
    ],
    [
        'number' => 2,
        'iconName' => 'edit',
        'title' => $this->translate('I create an empty quiz'),
        'text' => $this->translate('To create an empty quiz, go to create quiz in the navigation bar when logged in.'),
    ],
    [
        'number' => 3,
        'iconName' => 'plus-sign',
        'title' => $this->translate('I add questions to the quiz'),
        'text' => sprintf($this->translate('Please read the %sadd a new question</a> section for a more detailed information.'),$addNewQuestionLink),
    ],
    [
        'number' => 4,
        'iconName' => 'trophy',
        'title' => $this->translate('I can check that my quiz has been published'),
        'text' => $this->translate('Automatically the quiz will be published and available when browsing the different quiz.'),
    ],
];
?>
<p><?php echo $this->translate('To create a quiz, here are the steps you have to complete.'); ?></p>        
<ul class="unstyled">
    <?php echo $this->partialLoop('lrnl-help/help-static/step.phtml',$createListSteps); ?>
</ul>  
