<?php
$title = $this->translate('Recommendation for publishing quizes');
$this->headTitle($title);
$ourMethodLink = '<a href="'.$this->url('staticpages/template',['template' => 'about_our_method']).'">';
$site = $this->site();
?>
<p><?php echo sprintf($this->translate('In order to have the best experience with %s, we recommend reading and applying following rules: '),$site); ?></p>
<ul class="unstyled">
    <li>
        <h4><?php echo $this->translate('Use clear and explicit name for your quizes'); ?></h4>
        <p><?php echo $this->translate('Due to the great amount of quizes, the naming policy is key to help the user finding the quiz.'); ?></p>
    </li>    
    <li>
        <h4><?php echo $this->translate('Make extensive use of tags'); ?></h4>
        <p><?php echo $this->translate('Using tags makes it easier for your quizes to be found and used. It can be redondant with the title. Typically you should use around 5 tags.'); ?></p>
    </li>    
    <li>
        <h4><?php echo $this->translate('Do not create quizes with too many questions : between 15 and 50 is ok'); ?></h4>
        <p><?php echo $this->translate('We know that concentration is limited. Therefore in order to optimize learning the quizes should not be too long.'); ?></p>
    </li>
<?php if ($this->hasRole('teacher') || $this->hasRole('admin')): ?>
    <li>
        <h4><?php echo $this->translate('Try to order the question around a theme can help the learner'); ?></h4>
        <p><?php echo sprintf($this->translate('The more connections between the different questions the better for the learning process. See the %sour method</a> for more information.'),$ourMethodLink); ?></p>
    </li>
    <li>
        <h4><?php echo $this->translate('Add comments to every question'); ?></h4>
        <p><?php echo $this->partial('lrnl-help/help-static/write_comments'); ?></p>
    </li>
<?php endif; ?>
</ul>




