<?php
$title = $this->translate('Welcome');
$this->headTitle($title);
$termsLink = '<a href="'.$this->url('staticpages/template',['template' => 'terms_imprint']).'">';
?>
<ul class="unstyled">
    <li>
        <h4><?php echo $this->translate('What is Learnlists?'); ?></h4>
        <p><?php echo $this->translate('Learnlists is a great way to learn through the best quality quizz with top learning methods'); ?></p>
    </li>    
    <li>
        <h4><?php echo $this->translate('Is Learnlists free?'); ?></h4>
        <p><?php echo sprintf($this->translate('Learnlists is completely free. All the contents is nevertheless protected. Please go the %sTerms</a> for more information.'),$termsLink); ?></p>
    </li>    
</ul>



