<h1>Register</h1>

<?php 
if(!$this->enableRegistration) {
    print '<div class="alert alert-error">Registration is disabled</div>';
    return;
}

$form = $this->registerForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/register/step2', array('token'=>$this->model->getRequestKey())));
$form->setAttribute('method', 'post');
$form->get('submit')->setValue($this->translate('Sign Up'));
?>  

<?php if ($form->getMessages()):?>
    <div class="alert alert-error">
        <button class="close" data-dismiss="alert" type="button">×</button>
        <strong><?php echo $this->translate('Try again!'); ?></strong>
    </div>
<?php endif;?>
<?php echo $this->form()->openTag($form); 
$formType = \DluTwBootstrap\Form\FormUtil::FORM_TYPE_VERTICAL;
foreach ($form as $element) {
    if ($element->getName() == 'submit'){
        echo $this->formActionsTwb([$element], $formType,['submit' => ['class' => 'btn-primary']]);
    } else if ($element->getName() != 'email'){
        echo $this->formRowTwb($element, $formType);
    }
}
echo $this->form()->closeTag() ?>

    <?php if ($this->redirect): ?>
        <input type="hidden" name="redirect" value="<?php echo $this->redirect ?>" />
    <?php endif ?>
    <input type="hidden" name="email" value="<?php echo $this->escapeHtmlAttr($this->model->getEmailAddress()); ?>" />
<?php echo $this->form()->closeTag() ?>
