<?php

use DluTwBootstrap\Form\FormUtil;

$title = $this->translate('Sign In');
$this->headTitle($title);

$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login'));
$form->setAttribute('method', 'post');
$form->get('identity')->setLabel(_('Email or Username'));
$form->get('credential')->setLabel(_('Password'));
$form->get('submit')->setValue(_('Sign in'))->setLabel('');

$formType  = FormUtil::FORM_TYPE_VERTICAL;
$displayOptions = [
    'elements' => [
        'submit' => [
            'class' => 'btn-primary',
            'label' => false
        ],
    ],
];
?>
<h1><?php echo $title ?></h1>
<?php if ($form->getMessages()): ?>
<div class="alert alert-error">
    <button class="close" data-dismiss="alert" type="button">×</button>
    <strong><?php echo $this->translate('Try again!'); ?></strong>
</div>
<?php endif; ?>
<?php echo $this->form()->openTag($form) ?>
    <?php echo $this->formRowTwb($form->get('identity',$formType));?>
    <?php echo $this->formRowTwb($form->get('credential'), $formType);?>
<?php if ($form->get('remember_me')) : ?>
    <label class="checkbox">
        <?php echo $this->formInput($form->get('remember_me')); ?> <?php echo $this->formLabel($form->get('remember_me')); ?>
    </label>
<?php endif; ?>
    <p>
        <a href="<?php echo $this->url('zfcuser/forgotpassword') ?>">
            <?php echo $this->translate('Forgot your password?'); ?>
        </a>
    </p>
    <?php echo $this->formActionsTwb([$form->get('submit')], $formType, $displayOptions['elements']);?>
    <?php if ($this->redirect): ?>
    <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
    <?php endif ?>
<?php echo $this->form()->closeTag() ?>

