<?php
$title = $this->translate('Sign In');
$this->headTitle($title);
?>
<h1><?php echo $title ?></h1>

<?php
$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login'));
$form->setAttribute('method', 'post');
$form->get('identity')->setLabel(_('Email or Username'));
$form->get('credential')->setLabel(_('Password'));
$form->get('submit')->setValue(_('Sign in'));

if ($form->getMessages()):
?>
    <div class="alert alert-error">
        <button class="close" data-dismiss="alert" type="button">×</button>
        <strong><?php echo $this->translate('Try again!'); ?></strong>
    </div>
<?php
endif;
?>

<?php echo $this->form()->openTag($form) ?>
    
        <?php echo $this->formTwb($form, \DluTwBootstrap\Form\FormUtil::FORM_TYPE_VERTICAL,['elements' => ['submit' => ['class' => 'btn-primary']]]);?>

        <label class="checkbox">
            <?php //echo $this->formCheckbox($form->get('remember_me')) ?> <?php //echo $form->get('remember_me')->getLabel() ?>
        </label>
        
        <?php if ($this->redirect): ?>
        <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
        <?php endif ?>

<?php echo $this->form()->closeTag() ?>
<p><a href="<?php echo $this->url('zfcuser/forgotpassword') ?>"><?php echo $this->translate('Forgot your password?'); ?></a></p>
<?php if ($this->enableRegistration) : ?>
<?php echo $this->translate('Not registered?'); ?> <a href="<?php echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect='.$this->redirect : '') ?>"><?php echo $this->translate('Sign Up!'); ?></a>
<?php endif; ?>
