<?php
$title = $this->translate('About our methods');
$this->headTitle($title);
?>
<h1><?php echo $title; ?></h1>
<p>
    Our method for learning have been developed in order to be as efficient and sustainable as possible. They rely on following key principles. 
</p>
<ul>
    <h3>Our key principles: </h3>
    <li>
        Forget and remember : the repetition ist one of the best way to learn
    </li>
    <li>
        Create link with other experience: repeat should be always different and always linked to other repetitions.
    </li>
    <li>
        Create feeling and pleasure: serious games helps also significantly improve the way we remember.
    </li>
</ul>

